"""Reviewed S1/S2 financial vocabulary; changes require a new reviewed revision."""

from enum import StrEnum


class Concept(StrEnum):
    """A normalized concept never implies a missing value is zero."""

    REVENUE = "revenue"
    COST_OF_REVENUE = "cost_of_revenue"
    GROSS_PROFIT = "gross_profit"
    RESEARCH_AND_DEVELOPMENT_EXPENSE = "research_and_development_expense"
    SELLING_GENERAL_AND_ADMINISTRATIVE_EXPENSE = "selling_general_and_administrative_expense"
    OPERATING_EXPENSES = "operating_expenses"
    OPERATING_INCOME = "operating_income"
    INTEREST_EXPENSE = "interest_expense"
    PRETAX_INCOME = "pretax_income"
    INCOME_TAX_EXPENSE = "income_tax_expense"
    NET_INCOME_PARENT = "net_income_parent"
    NET_INCOME_CONSOLIDATED = "net_income_consolidated"
    EPS_BASIC = "eps_basic"
    EPS_DILUTED = "eps_diluted"
    WEIGHTED_AVERAGE_SHARES_BASIC = "weighted_average_shares_basic"
    WEIGHTED_AVERAGE_SHARES_DILUTED = "weighted_average_shares_diluted"
    COMMON_SHARES_OUTSTANDING = "common_shares_outstanding"
    CASH_AND_CASH_EQUIVALENTS = "cash_and_cash_equivalents"
    SHORT_TERM_INVESTMENTS = "short_term_investments"
    ACCOUNTS_RECEIVABLE_NET = "accounts_receivable_net"
    INVENTORY_NET = "inventory_net"
    CURRENT_ASSETS = "current_assets"
    PROPERTY_PLANT_EQUIPMENT_NET = "property_plant_equipment_net"
    GOODWILL = "goodwill"
    INTANGIBLE_ASSETS_NET_EXCLUDING_GOODWILL = "intangible_assets_net_excluding_goodwill"
    TOTAL_ASSETS = "total_assets"
    ACCOUNTS_PAYABLE_CURRENT = "accounts_payable_current"
    CURRENT_DEBT = "current_debt"
    LONG_TERM_DEBT_NONCURRENT = "long_term_debt_noncurrent"
    CURRENT_LIABILITIES = "current_liabilities"
    TOTAL_LIABILITIES = "total_liabilities"
    EQUITY_PARENT = "equity_parent"
    EQUITY_INCLUDING_NONCONTROLLING_INTERESTS = "equity_including_noncontrolling_interests"
    NONCONTROLLING_INTERESTS = "noncontrolling_interests"
    CASH_FROM_OPERATING_ACTIVITIES = "cash_from_operating_activities"
    CAPITAL_EXPENDITURES_PPE = "capital_expenditures_ppe"
    DEPRECIATION_AND_AMORTIZATION = "depreciation_and_amortization"
    SHARE_BASED_COMPENSATION = "share_based_compensation"
    DIVIDENDS_PAID = "dividends_paid"
    SHARE_REPURCHASES = "share_repurchases"
