// Generated by scripts/export_monitor_snapshot.py; saved real check, no live polling.
import type { MonitorSnapshot } from "./monitorTypes";

const snapshot = {
  "kind": "real-filing-monitor-snapshot",
  "outcome": "no_change",
  "outcomeLabel": "No new scoped filings",
  "baselineEligible": true,
  "checkedAt": "2026-09-21T20:36:50.335318Z",
  "requestId": "be853bd4-9847-4fc0-beaf-d33de1e8ee86",
  "executionId": "b70b17cc-e7d1-471e-8207-c6bb9f9934ec",
  "requestSha256": "29c179eacf915a5b2164c480cf43099411e508ca9303451688ff0bf245dc75d4",
  "auditSha256": "ee1074c19265159a08abe95bf8a6795b2c6090bacbccf8875e34b0a6ee577794",
  "manifestSha256": "9e48e428b7bdd4f60e38326a21f697312aa34bef76339a29c3978d3a3dbd8c04",
  "baseline": {
    "kind": "initial_seed",
    "requestId": "19340d60-6544-4ac5-8d69-241f166e28a1",
    "executionId": "d5e8458f-da16-4b83-a371-1572e8e625a7",
    "cutoff": "2026-09-21T17:07:35.880159Z",
    "manifestSha256": "135f9e9f468836ecceadc1317efaaa3f9f91190795f23b96f674fa60161910ad",
    "captureIds": [
      "0e93340d-a10c-40eb-b463-047c23be58bf"
    ]
  },
  "cutoff": "2026-09-21T20:32:51Z",
  "filedStart": "2025-01-01",
  "filedEnd": "2026-09-21",
  "forms": [
    "10-K",
    "10-K/A",
    "10-Q",
    "10-Q/A"
  ],
  "coverage": {
    "baseline": "complete",
    "current": "complete"
  },
  "flags": [],
  "newFilings": [],
  "amendments": [],
  "filings": [
    {
      "accession": "0001628280-25-039781",
      "form": "10-Q",
      "filedDate": "2025-08-12",
      "reportDate": "2025-06-30",
      "acceptanceAt": "2025-08-12T13:21:01Z",
      "sourceLocator": "/filings/recent/325",
      "captureId": "0e93340d-a10c-40eb-b463-047c23be58bf",
      "capturedAt": "2026-09-21T17:07:35.957888Z",
      "url": "https://data.sec.gov/submissions/CIK0001876042.json",
      "sha256": "c4f43a9e2582ab88f8cfa1d8f3527bfbf515770e3c33766e21629845c16026a3"
    },
    {
      "accession": "0001876042-25-000047",
      "form": "10-Q",
      "filedDate": "2025-11-12",
      "reportDate": "2025-09-30",
      "acceptanceAt": "2025-11-12T14:21:02Z",
      "sourceLocator": "/filings/recent/279",
      "captureId": "0e93340d-a10c-40eb-b463-047c23be58bf",
      "capturedAt": "2026-09-21T17:07:35.957888Z",
      "url": "https://data.sec.gov/submissions/CIK0001876042.json",
      "sha256": "c4f43a9e2582ab88f8cfa1d8f3527bfbf515770e3c33766e21629845c16026a3"
    },
    {
      "accession": "0001876042-26-000062",
      "form": "10-K",
      "filedDate": "2026-03-09",
      "reportDate": "2025-12-31",
      "acceptanceAt": "2026-03-09T12:36:51Z",
      "sourceLocator": "/filings/recent/177",
      "captureId": "0e93340d-a10c-40eb-b463-047c23be58bf",
      "capturedAt": "2026-09-21T17:07:35.957888Z",
      "url": "https://data.sec.gov/submissions/CIK0001876042.json",
      "sha256": "c4f43a9e2582ab88f8cfa1d8f3527bfbf515770e3c33766e21629845c16026a3"
    },
    {
      "accession": "0001876042-26-000150",
      "form": "10-Q",
      "filedDate": "2026-05-11",
      "reportDate": "2026-03-31",
      "acceptanceAt": "2026-05-11T13:16:55Z",
      "sourceLocator": "/filings/recent/118",
      "captureId": "0e93340d-a10c-40eb-b463-047c23be58bf",
      "capturedAt": "2026-09-21T17:07:35.957888Z",
      "url": "https://data.sec.gov/submissions/CIK0001876042.json",
      "sha256": "c4f43a9e2582ab88f8cfa1d8f3527bfbf515770e3c33766e21629845c16026a3"
    },
    {
      "accession": "0001876042-26-000228",
      "form": "10-K/A",
      "filedDate": "2026-07-13",
      "reportDate": "2025-12-31",
      "acceptanceAt": "2026-07-13T20:40:02Z",
      "sourceLocator": "/filings/recent/48",
      "captureId": "0e93340d-a10c-40eb-b463-047c23be58bf",
      "capturedAt": "2026-09-21T17:07:35.957888Z",
      "url": "https://data.sec.gov/submissions/CIK0001876042.json",
      "sha256": "c4f43a9e2582ab88f8cfa1d8f3527bfbf515770e3c33766e21629845c16026a3"
    },
    {
      "accession": "0001876042-26-000248",
      "form": "10-Q",
      "filedDate": "2026-08-05",
      "reportDate": "2026-06-30",
      "acceptanceAt": "2026-08-05T13:02:57Z",
      "sourceLocator": "/filings/recent/36",
      "captureId": "0e93340d-a10c-40eb-b463-047c23be58bf",
      "capturedAt": "2026-09-21T17:07:35.957888Z",
      "url": "https://data.sec.gov/submissions/CIK0001876042.json",
      "sha256": "c4f43a9e2582ab88f8cfa1d8f3527bfbf515770e3c33766e21629845c16026a3"
    }
  ],
  "filingCount": 6,
  "newCount": 0,
  "amendmentCount": 0,
  "blockers": [
    "handoff_not_implemented",
    "financial_coverage_not_reviewed",
    "quote_registration_missing"
  ],
  "knownLimits": "Advertised Submissions documents within the pinned filed window; acceptance metadata is not proof of historical public availability. No event or accounting restatement review.",
  "history": {
    "baseline": {
      "required": [],
      "excluded_nonoverlap": []
    },
    "current": {
      "required": [],
      "excluded_nonoverlap": []
    }
  },
  "amendmentMeaning": "Separate filing edition; no restatement or non-reliance inference",
  "attempts": [
    {
      "id": "40045a2f-f1f3-49eb-bea1-72a906e69544",
      "status": 200,
      "state": "content_unchanged",
      "requestedAt": "2026-09-21T20:36:50.211096Z",
      "finishedAt": "2026-09-21T20:36:50.335318Z",
      "reusedCaptureId": "0e93340d-a10c-40eb-b463-047c23be58bf",
      "payloadSha256": "c4f43a9e2582ab88f8cfa1d8f3527bfbf515770e3c33766e21629845c16026a3",
      "payloadBytes": 66909
    }
  ],
  "counts": [
    {
      "id": "source_bootstrap",
      "label": "Acquisition requests",
      "value": 3
    },
    {
      "id": "sec_filing_monitor",
      "label": "Filing checks",
      "value": 1
    },
    {
      "id": "source_captures",
      "label": "Logical captures",
      "value": 12
    },
    {
      "id": "source_fetch_attempts",
      "label": "Fetch attempts",
      "value": 13
    },
    {
      "id": "source_attempt_payloads",
      "label": "Retained monitor bodies",
      "value": 1
    },
    {
      "id": "normalization_batches",
      "label": "Normalization batches",
      "value": 0
    }
  ]
} satisfies MonitorSnapshot;

export default snapshot;
