// Generated by scripts/export_scheduler_snapshot.py; saved manual state.
import type { SchedulerSnapshot } from "./schedulerTypes";

const snapshot = {
  "kind": "real-filing-scheduler-snapshot",
  "asOf": "2026-09-21T22:08:24.262232Z",
  "auditSha256": "1b1ddb429521ab8c2593c69b0b6994c61b0c978aa5cfdb96f002bfd92a3859c2",
  "scheduleId": "7a5b20c1-ad07-4f9a-a7bf-3915824364f2",
  "revisionId": "5d7ab147-e9d4-4b30-b6c1-a6e04e61d838",
  "epoch": 2,
  "configSha256": "c3e95be7a93c672d3cf2bd148b0867e683de8dd4dff1b76d7e9864f533e63461",
  "active": false,
  "health": "paused",
  "service": "not_configured",
  "healthMeaning": "Configuration readiness only; no registered background worker.",
  "reasons": [
    "budget_reservation_full"
  ],
  "filedStart": "2025-01-01",
  "filedEnd": "2026-09-21",
  "cadenceSeconds": 3600,
  "jitterSeconds": 0,
  "budgetUnits": 3,
  "reservedUnits": 3,
  "actualAttempts": 1,
  "lastTickAt": "2026-09-21T22:08:23.591967Z",
  "lastHttpCompletedAt": "2026-09-21T22:07:33.362718Z",
  "lastSuccessAt": "2026-09-21T22:07:33.362718Z",
  "lastSuccessCutoff": "2026-09-21T22:07:00.000000Z",
  "nextDueAt": "2026-09-21T23:07:00.000000Z",
  "nextDueActionable": false,
  "lagSeconds": 0,
  "retryAt": null,
  "failures": 0,
  "missedIntervals": [],
  "slots": [
    {
      "index": 0,
      "requestId": "59ca04e0-e3a1-48c3-99b4-9d8238d5dd3c",
      "executionId": "9122ba10-9e2e-46f5-86d6-f45cd8ee24e6",
      "nominalAt": "2026-09-21T22:07:00.000000Z",
      "dueAt": "2026-09-21T22:07:00.000000Z",
      "state": "completed",
      "availableAt": "2026-09-21T22:07:13.807448Z",
      "attemptNumber": 1,
      "outcome": "no_change",
      "outcomeLabel": "No new scoped filings",
      "checkedAt": "2026-09-21T22:07:33.362718Z",
      "eligible": true,
      "manifestSha256": "ad29266a48bb38bcc511f10711f332cbbb627de16c6b53e605d9ff843e6419f2",
      "planSha256": "05dd743cc76661feb2c806faeee35cd99a25041c9d80de5d2af2f9d7584abe6f",
      "baselineRequestId": "be853bd4-9847-4fc0-beaf-d33de1e8ee86",
      "baselineManifestSha256": "9e48e428b7bdd4f60e38326a21f697312aa34bef76339a29c3978d3a3dbd8c04",
      "filings": 6,
      "newFilings": 0,
      "amendments": 0,
      "coverage": {
        "baseline": "complete",
        "current": "complete"
      }
    }
  ],
  "attempts": [
    {
      "id": "6083029b-7fea-44e6-9d00-be593569db15",
      "state": "content_unchanged",
      "status": 200,
      "requestedAt": "2026-09-21T22:07:33.107044Z",
      "finishedAt": "2026-09-21T22:07:33.362718Z",
      "payloadSha256": "c4f43a9e2582ab88f8cfa1d8f3527bfbf515770e3c33766e21629845c16026a3",
      "payloadBytes": 66909,
      "reusedCaptureId": "0e93340d-a10c-40eb-b463-047c23be58bf"
    }
  ],
  "revisions": [
    {
      "epoch": 1,
      "at": "2026-09-21T22:06:49.639149Z",
      "active": true,
      "reason": "D036 coordinator approval; one manual CRCL slot then pause",
      "configSha256": "9b8bda7073d5bfc09050b4f16e165b310240fb02df086666af59df2e1cdedf38"
    },
    {
      "epoch": 2,
      "at": "2026-09-21T22:08:23.923209Z",
      "active": false,
      "reason": "D036 explicit operator pause",
      "configSha256": "c3e95be7a93c672d3cf2bd148b0867e683de8dd4dff1b76d7e9864f533e63461"
    }
  ],
  "events": [
    {
      "kind": "created",
      "at": "2026-09-21T22:06:49.639895Z",
      "key": "created"
    },
    {
      "kind": "materialized",
      "at": "2026-09-21T22:07:13.809463Z",
      "key": "slot:0"
    },
    {
      "kind": "resolved",
      "at": "2026-09-21T22:07:33.398934Z",
      "key": "resolved:99a45d1a-be3a-42a5-abcd-4d20e6f07abf"
    },
    {
      "kind": "revised",
      "at": "2026-09-21T22:08:23.923640Z",
      "key": "revision:5d7ab147-e9d4-4b30-b6c1-a6e04e61d838"
    }
  ],
  "counts": [
    {
      "id": "normalization_batches",
      "value": 0
    },
    {
      "id": "sec_filing_monitor",
      "value": 2
    },
    {
      "id": "security_identifiers",
      "value": 0
    },
    {
      "id": "source_attempt_payloads",
      "value": 2
    },
    {
      "id": "source_bootstrap",
      "value": 3
    },
    {
      "id": "source_captures",
      "value": 12
    },
    {
      "id": "source_fetch_attempts",
      "value": 14
    },
    {
      "id": "watchlist_memberships",
      "value": 0
    }
  ]
} satisfies SchedulerSnapshot;

export default snapshot;
