// Generated by scripts/export_pipeline_snapshot.py; do not hand edit.
// Sanitized development snapshot, not a live status service or S6 API.
import type { PipelineSnapshot } from "./types";

const snapshot = {
  "kind": "real-application-pipeline-snapshot",
  "ticker": "CRCL",
  "reviewedOn": "2026-09-21",
  "acquisitionVerifiedAt": "2026-09-21T17:08:44.789858Z",
  "reviewCheckpoint": "61524a7 / milestone/d3d-identity-review",
  "requestId": "19340d60-6544-4ac5-8d69-241f166e28a1",
  "executionId": "d5e8458f-da16-4b83-a371-1572e8e625a7",
  "acquisitionAuditSha256": "4b1bff12335faf50b67192f92f0f04a5f7d8d1ff8738644f037acf8036836dac",
  "identityAuditSha256": "4f6c25d275d87ecd41a6b40ade9eb2cb75179a9b385dc554cc24ea2ab4474c99",
  "counts": [
    {
      "id": "source_captures",
      "label": "Captures",
      "value": 12
    },
    {
      "id": "source_fetch_attempts",
      "label": "Fetch attempts",
      "value": 12
    },
    {
      "id": "analysis_requests",
      "label": "Bootstrap requests",
      "value": 3
    },
    {
      "id": "issuers",
      "label": "Issuer records",
      "value": 1
    },
    {
      "id": "securities",
      "label": "Security records",
      "value": 1
    },
    {
      "id": "security_identifiers",
      "label": "Quote identifiers",
      "value": 0
    },
    {
      "id": "watchlist_memberships",
      "label": "Watchlist memberships",
      "value": 0
    },
    {
      "id": "normalization_batches",
      "label": "Normalization batches",
      "value": 0
    }
  ],
  "captures": [
    {
      "id": "923841dc-5a9b-44c4-b59b-ddf7e567fc3b",
      "label": "Company Facts",
      "url": "https://data.sec.gov/api/xbrl/companyfacts/CIK0001876042.json",
      "sha256": "f7139545b482a7b31520225bc155cb41241b82f004eb8fbca55f4ab66d1426af",
      "bytes": 455994,
      "httpStatus": 200,
      "requestedAt": "2026-09-21T17:07:35.667129Z",
      "capturedAt": "2026-09-21T17:07:35.819182Z"
    },
    {
      "id": "0e93340d-a10c-40eb-b463-047c23be58bf",
      "label": "Issuer Submissions",
      "url": "https://data.sec.gov/submissions/CIK0001876042.json",
      "sha256": "c4f43a9e2582ab88f8cfa1d8f3527bfbf515770e3c33766e21629845c16026a3",
      "bytes": 66909,
      "httpStatus": 200,
      "requestedAt": "2026-09-21T17:07:35.880159Z",
      "capturedAt": "2026-09-21T17:07:35.957888Z"
    },
    {
      "id": "7cdba2c5-76a0-453d-b8fb-cae4b6e77809",
      "label": "FY2025 annual report",
      "url": "https://www.sec.gov/Archives/edgar/data/1876042/000187604226000062/crcl-20251231.htm",
      "sha256": "e535360770ac9230b871b4a4f9ab74336f790aa089f3dd0a078be83e517bbd4c",
      "bytes": 3721200,
      "httpStatus": 200,
      "requestedAt": "2026-09-21T17:07:36.089291Z",
      "capturedAt": "2026-09-21T17:07:36.472331Z"
    },
    {
      "id": "a091bf37-ac2e-4ba8-8500-77c59e0da24a",
      "label": "FY2025 annual amendment",
      "url": "https://www.sec.gov/Archives/edgar/data/1876042/000187604226000228/crcl-20251231.htm",
      "sha256": "10419022aa21286368e02b193c224af7ad5e059f828ee60c436128c344f51325",
      "bytes": 99909,
      "httpStatus": 200,
      "requestedAt": "2026-09-21T17:07:36.487790Z",
      "capturedAt": "2026-09-21T17:07:36.604156Z"
    },
    {
      "id": "e58aaf2d-ba12-417e-9b2d-872df7a10610",
      "label": "Q2 2026 quarterly report",
      "url": "https://www.sec.gov/Archives/edgar/data/1876042/000187604226000248/crcl-20260630.htm",
      "sha256": "81d3190308738e630e9424cc29897d492e943912525ab5f5b03612a160b60cb6",
      "bytes": 2076678,
      "httpStatus": 200,
      "requestedAt": "2026-09-21T17:07:36.701570Z",
      "capturedAt": "2026-09-21T17:07:36.842185Z"
    }
  ],
  "identityFields": [
    {
      "id": "cik",
      "label": "SEC issuer identifier (CIK)",
      "value": "0001876042",
      "status": "supported",
      "evidence": [
        {
          "captureId": "0e93340d-a10c-40eb-b463-047c23be58bf",
          "locator": "/cik",
          "excerpt": "0001876042"
        }
      ]
    },
    {
      "id": "name",
      "label": "Issuer name",
      "value": "Circle Internet Group, Inc.",
      "status": "supported",
      "evidence": [
        {
          "captureId": "0e93340d-a10c-40eb-b463-047c23be58bf",
          "locator": "/name",
          "excerpt": "Circle Internet Group, Inc."
        }
      ]
    },
    {
      "id": "symbol",
      "label": "Trading symbol",
      "value": "CRCL",
      "status": "supported",
      "evidence": [
        {
          "captureId": "0e93340d-a10c-40eb-b463-047c23be58bf",
          "locator": "/tickers/0",
          "excerpt": "CRCL"
        },
        {
          "captureId": "7cdba2c5-76a0-453d-b8fb-cae4b6e77809",
          "locator": "/*/*[2]/*[32]/*/*[3]/*[3]/*/*/ix:nonNumeric",
          "excerpt": "CRCL"
        },
        {
          "captureId": "a091bf37-ac2e-4ba8-8500-77c59e0da24a",
          "locator": "/*/*[2]/*[33]/*/*[3]/*[3]/*/*/ix:nonNumeric",
          "excerpt": "CRCL"
        },
        {
          "captureId": "e58aaf2d-ba12-417e-9b2d-872df7a10610",
          "locator": "/*/*[2]/*[32]/*/*[3]/*[3]/*/*/ix:nonNumeric",
          "excerpt": "CRCL"
        }
      ]
    },
    {
      "id": "exchange_code",
      "label": "Exchange code",
      "value": "NYSE",
      "status": "supported",
      "evidence": [
        {
          "captureId": "0e93340d-a10c-40eb-b463-047c23be58bf",
          "locator": "/exchanges/0",
          "excerpt": "NYSE"
        },
        {
          "captureId": "7cdba2c5-76a0-453d-b8fb-cae4b6e77809",
          "locator": "/*/*[2]/*[32]/*/*[3]/*[5]/*/*/ix:nonNumeric",
          "excerpt": "New York Stock Exchange"
        },
        {
          "captureId": "a091bf37-ac2e-4ba8-8500-77c59e0da24a",
          "locator": "/*/*[2]/*[33]/*/*[3]/*[5]/*/*/ix:nonNumeric",
          "excerpt": "New York Stock Exchange"
        },
        {
          "captureId": "e58aaf2d-ba12-417e-9b2d-872df7a10610",
          "locator": "/*/*[2]/*[32]/*/*[3]/*[5]/*/*/ix:nonNumeric",
          "excerpt": "New York Stock Exchange"
        }
      ]
    },
    {
      "id": "share_class",
      "label": "Share class",
      "value": "Class A common stock",
      "status": "supported",
      "evidence": [
        {
          "captureId": "7cdba2c5-76a0-453d-b8fb-cae4b6e77809",
          "locator": "/*/*[2]/*[32]/*/*[3]/*[1]/*/*/ix:nonNumeric",
          "excerpt": "Class A common stock, par value $0.0001 per share"
        },
        {
          "captureId": "a091bf37-ac2e-4ba8-8500-77c59e0da24a",
          "locator": "/*/*[2]/*[33]/*/*[3]/*[1]/*/*/ix:nonNumeric",
          "excerpt": "Class A common stock, par value $0.0001 per share"
        },
        {
          "captureId": "e58aaf2d-ba12-417e-9b2d-872df7a10610",
          "locator": "/*/*[2]/*[32]/*/*[3]/*[1]/*/*/ix:nonNumeric",
          "excerpt": "Class A common stock, par value $0.0001 per share"
        }
      ]
    },
    {
      "id": "valid_from",
      "label": "Listing start",
      "value": "2025-06-05",
      "status": "supported",
      "evidence": [
        {
          "captureId": "7cdba2c5-76a0-453d-b8fb-cae4b6e77809",
          "locator": "/*/*[2]/*[1104]/*",
          "excerpt": "Since June 5, 2025, our Class A common stock has been listed on the New York Stock Exchange under the symbol CRCL."
        }
      ]
    },
    {
      "id": "quote_currency",
      "label": "Quote currency",
      "value": null,
      "status": "unsubstantiated",
      "evidence": []
    }
  ],
  "reportingCurrencyEvidence": [
    {
      "captureId": "7cdba2c5-76a0-453d-b8fb-cae4b6e77809",
      "locator": "/*/*[2]/*[1495]/*[1]",
      "excerpt": "Our reporting currency is the U.S. dollar and the functional currency of our international operations is its local currency."
    },
    {
      "captureId": "e58aaf2d-ba12-417e-9b2d-872df7a10610",
      "locator": "/*/*[2]/*[713]/*[1]",
      "excerpt": "Our reporting currency is the U.S. dollar and the functional currency of our international operations is its local currency."
    }
  ],
  "plan": {
    "inventoryStart": "2025-01-01",
    "inventoryEnd": "2026-09-21",
    "resources": [
      "Company Facts",
      "Issuer Submissions",
      "FY2025 annual report",
      "FY2025 annual amendment",
      "Q2 2026 quarterly report"
    ],
    "hash": "ef20189a84b51fcde081ee216b3b97d6e058e01d3ea6dbd7767c5657271389b0",
    "policy": "SEC public filings · reviewed 2026-09-21"
  },
  "blocker": {
    "code": "quote_currency_unsubstantiated",
    "title": "Quote currency needs source evidence",
    "explanation": "The reviewed captures do not explicitly establish the currency in which CRCL's NYSE Class A shares are quoted. Reporting currency and offering-price units cannot fill this gap.",
    "nextAction": "Obtain an issuer or exchange statement, or an entitled reference-data record, explicitly binding Circle Class A / CRCL / NYSE to quotation currency with effective-date context. Verify retention rights and capture it through a reviewed acquisition path before registration."
  },
  "stages": [
    {
      "id": "plan",
      "number": "01",
      "label": "Pinned acquisition plan",
      "status": "verified",
      "statusLabel": "Pinned",
      "summary": "The request fixes its issuer, reviewed source policy, inventory window and five exact resources."
    },
    {
      "id": "captures",
      "number": "02",
      "label": "Source captures",
      "status": "verified",
      "statusLabel": "Captured",
      "summary": "Five successful captures belong to this pinned request. The application totals below include earlier bootstrap requests."
    },
    {
      "id": "identity",
      "number": "03",
      "label": "Identity review",
      "status": "gap",
      "statusLabel": "Reviewed · one gap",
      "summary": "Issuer identity, share class and listing start are supported. Quote currency remains unsubstantiated."
    },
    {
      "id": "registration",
      "number": "04",
      "label": "Quote registration",
      "status": "blocked",
      "statusLabel": "Blocked",
      "summary": "No quote identifier has been registered. Capture readiness only enabled an identity review."
    },
    {
      "id": "normalization",
      "number": "05",
      "label": "Financial normalization",
      "status": "not-started",
      "statusLabel": "Not started",
      "summary": "No application normalization batch has been created. Stored source bodies are not published financial facts."
    },
    {
      "id": "analysis",
      "number": "06",
      "label": "Analysis / publication",
      "status": "not-started",
      "statusLabel": "Not started",
      "summary": "Ordinary analysis is blocked. There is no completed financial analysis or published result from these requests."
    }
  ],
  "currencySearch": {
    "reviewedOn": "2026-09-21",
    "sha256": "229c3ac229324e209bc72adddfbaf29d09928e3058174bb94f34bbb5bdb41b5a",
    "basis": "Authored research notes from bounded primary-source inspection; not archived application evidence.",
    "summary": "No qualifying quotation-currency evidence acquired. The existing registration blocker remains.",
    "effectiveDateRule": "The supported 2025-06-05 listing start does not establish a currency effective date. A current quote or retrieval time cannot be backdated to the IPO.",
    "nextAction": "Obtain an issuer or exchange statement, or an entitled reference-data record, explicitly binding Circle Class A / CRCL / NYSE to quotation currency with effective-date context. Verify retention rights and capture it through a reviewed acquisition path before registration.",
    "sources": [
      {
        "id": "sec-filings",
        "label": "Archived SEC identity review",
        "url": "https://www.sec.gov/Archives/edgar/data/1876042/000187604226000062/crcl-20251231.htm",
        "statusLabel": "Currency has a different meaning",
        "method": "Replay of pinned D3c application captures under D3d review; targeted SEC discovery search.",
        "finding": "The reviewed filings support issuer, Class A, symbol, exchange and listing start. Reporting currency and offering-price units do not establish exchange quotation currency.",
        "dateContext": "Listing start is supported from 2025-06-05; quotation-currency effective date remains unknown.",
        "policy": "Existing reviewed SEC scope and immutable captures remain valid. No new SEC capture was needed for this replay.",
        "links": []
      },
      {
        "id": "nyse-quote",
        "label": "NYSE CRCL quote page",
        "url": "https://www.nyse.com/quote/XNYS:CRCL",
        "statusLabel": "Explicit currency not established",
        "method": "Public page and identity/currency fields in responses delivered by a normal browser load.",
        "finding": "The filter response identified Circle, CRCL and XNYS. The inspected quote response exposed a quote timestamp but no explicit quotation-currency field. Displayed prices or the word dollars cannot establish USD. No raw response was retained in application storage.",
        "dateContext": "The displayed quote was dated 2026-09-21; this is not evidence of quotation currency since the listing start.",
        "policy": "ICE website terms do not establish an approved retained automated-ingestion policy. Reachable public endpoints are not a permission grant.",
        "links": [
          {
            "label": "ICE website terms",
            "url": "https://www.ice.com/privacy-security-center/terms-of-use"
          }
        ]
      },
      {
        "id": "circle-ir",
        "label": "Circle investor stock information",
        "url": "https://investor.circle.com/stock-info/",
        "statusLabel": "Quote evidence unavailable",
        "method": "Public text extraction, issuer FAQ and ordinary browser inspection.",
        "finding": "The extracted stock page contained quote section headings without populated currency evidence. The browser stopped at a Cloudflare security check; no bypass was attempted. The linked terms describe Circle Mint, so they were not treated as an IR quote-data retention grant.",
        "dateContext": "Research checked on 2026-09-21; no currency effective date obtained.",
        "policy": "Exact IR/Q4 quote-data retention scope remains unverified; no source policy activated.",
        "links": [
          {
            "label": "Investor FAQs",
            "url": "https://investor.circle.com/resources/investor-faqs/default.aspx"
          },
          {
            "label": "Linked Circle Mint agreement",
            "url": "https://www.circle.com/legal/user-agreement"
          }
        ]
      },
      {
        "id": "nyse-master",
        "label": "NYSE Group Security Master",
        "url": "https://www.nyse.com/data-products/catalog/nyse-group-security-master",
        "statusLabel": "Record and rights not obtained",
        "method": "Official product description, technical-document catalog and public sample directory inspection.",
        "finding": "The product offers reference files for the next trading session. No entitled CRCL record was obtained. The equity sample filenames inspected refer to vintages before the June 2025 listing, despite later directory modification dates; samples were not imported.",
        "dateContext": "A directory modification date is not a security record effective date. No qualifying CRCL currency interval was established.",
        "policy": "Purchase/access and retained-use entitlement remain unverified. No account, purchase or provider activation was performed.",
        "links": [
          {
            "label": "Technical documents",
            "url": "https://www.nyse.com/market-data/technical-documents"
          },
          {
            "label": "Public sample directory",
            "url": "https://ftp.nyse.com/Reference%20Data%20Samples/NYSE%20GROUP%20SECURITY%20MASTER/"
          }
        ]
      }
    ]
  }
} satisfies PipelineSnapshot;

export default snapshot;
