// Generated by scripts/generate_fundamentals_api.py. Do not edit.

export type FundamentalsPayload = {
  readonly "accounting": PublicAccounting | null;
  readonly "comparison_policy_hash": string;
  readonly "coverage": PublicCoverage;
  readonly "dependency_hash": string;
  readonly "evidence": ReadonlyArray<PublicEvidence>;
  readonly "evidence_mode": "synthetic";
  readonly "fixture_label": "Synthetic integration fixture \u2014 not company data";
  readonly "history": ReadonlyArray<PublicHistory>;
  readonly "metrics": ReadonlyArray<PublicMetric>;
  readonly "observations": ReadonlyArray<PublicObservation>;
  readonly "review_items": ReadonlyArray<PublicObservation>;
  readonly "selector": SelectionKey;
  readonly "trend": PublicTrend;
  readonly "version": "s6-fundamentals-v1";
};

export type HTTPValidationError = {
  readonly "detail"?: ReadonlyArray<ValidationError>;
};

export type LatestResponse = {
  readonly "latest_request_id": string;
  readonly "latest_request_state": "queued" | "running" | "waiting_for_input" | "retry_scheduled" | "completed" | "completed_with_gaps" | "failed" | "cancelled";
  readonly "snapshot": SnapshotResponse;
};

export type NoResult = {
  readonly "code": "snapshot_not_found" | "no_compatible_snapshot";
  readonly "message": string;
};

export type PublicAccounting = {
  readonly "input_indices": ReadonlyArray<number>;
  readonly "matches": boolean | null;
  readonly "period_end": string;
  readonly "reasons": ReadonlyArray<string>;
  readonly "residual": string | null;
  readonly "rule_revision": string;
  readonly "tolerance": string | null;
};

export type PublicCoverage = {
  readonly "applicable_count": number;
  readonly "counts": Readonly<Record<string, number>>;
  readonly "covered_count": number;
  readonly "fraction": string | null;
  readonly "revision": string;
  readonly "unresolved_count": number;
};

export type PublicEvidence = {
  readonly "absolute_error": string | null;
  readonly "accession": string | null;
  readonly "capture_ids": ReadonlyArray<string>;
  readonly "concept": string;
  readonly "filed_on": string | null;
  readonly "flags": ReadonlyArray<string>;
  readonly "input_index": number;
  readonly "mapping_revision_id": string;
  readonly "normalization_operation": "identity_decimal" | null;
  readonly "normalizer_revision": string;
  readonly "observation_ids": ReadonlyArray<string>;
  readonly "original_numeric_text": string | null;
  readonly "period_end": string;
  readonly "period_start": string | null;
  readonly "resolution_ids": ReadonlyArray<string>;
  readonly "retrieved_at": ReadonlyArray<string>;
  readonly "scope_hash": string;
  readonly "scope_kind": string;
  readonly "selection_hash": string;
  readonly "source_hashes": ReadonlyArray<string>;
  readonly "source_tag": string | null;
  readonly "source_url": string | null;
  readonly "transform_hash": string | null;
  readonly "unit": string;
  readonly "value": string | null;
};

export type PublicHistory = {
  readonly "eligible_snapshot_ids": ReadonlyArray<string>;
  readonly "excluded": ReadonlyArray<readonly [string, ReadonlyArray<string>]>;
  readonly "metric_id": string;
  readonly "minimum_samples": number;
  readonly "missing_quarter_ends": ReadonlyArray<string>;
  readonly "p25": string | null;
  readonly "p50": string | null;
  readonly "p75": string | null;
  readonly "reasons": ReadonlyArray<string>;
  readonly "relation": "below" | "within" | "above" | null;
  readonly "window_end": string;
  readonly "window_start": string;
  readonly "years": 3 | 5 | 10;
};

export type PublicMetric = {
  readonly "applicability": boolean | null;
  readonly "formula_revision": string;
  readonly "input_hash": string;
  readonly "input_indices": ReadonlyArray<number>;
  readonly "metric_id": string;
  readonly "operands": ReadonlyArray<PublicOperand>;
  readonly "reasons": ReadonlyArray<string>;
  readonly "status": "valid" | "not_meaningful" | "missing" | "invalid" | "stale" | "unsupported" | "inapplicable";
  readonly "unit": string;
  readonly "value": string | null;
};

export type PublicObservation = {
  readonly "category": string;
  readonly "metric_ids": ReadonlyArray<string>;
  readonly "rule_id": string;
  readonly "rule_revision": string;
  readonly "text": string;
  readonly "topic": string;
};

export type PublicOperand = {
  readonly "absolute_error": string | null;
  readonly "coefficients": ReadonlyArray<number>;
  readonly "formula_id": string;
  readonly "formula_revision": string;
  readonly "input_indices": ReadonlyArray<number>;
  readonly "period_end": string;
  readonly "period_start": string | null;
  readonly "reasons": ReadonlyArray<string>;
  readonly "review_hash": string;
  readonly "value": string | null;
};

export type PublicTrend = {
  readonly "changes": ReadonlyArray<string>;
  readonly "input_indices": ReadonlyArray<number>;
  readonly "input_reasons": ReadonlyArray<ReadonlyArray<string>>;
  readonly "input_statuses": ReadonlyArray<"valid" | "not_meaningful" | "missing" | "invalid" | "stale" | "unsupported" | "inapplicable">;
  readonly "period_ends": ReadonlyArray<string>;
  readonly "rates": ReadonlyArray<string | null>;
  readonly "reasons": ReadonlyArray<string>;
  readonly "relation": "rising" | "falling" | "broadly_stable" | "mixed" | null;
  readonly "rule_revision": string;
};

export type SelectionKey = {
  readonly "as_of": string;
  readonly "captured_before": string;
  readonly "currency": string;
  readonly "engine_revision": string;
  readonly "evaluated_at": string;
  readonly "filed_cutoff": string | null;
  readonly "freshness_revision": string;
  readonly "history_mode": "as_filed_by_date" | "original_as_filed" | "latest_reported";
  readonly "history_revision": string;
  readonly "history_years": 3 | 5 | 10;
  readonly "issuer_id": string;
  readonly "period_basis": "annual" | "quarter" | "ttm" | "instant";
  readonly "period_end": string;
  readonly "period_start": string | null;
  readonly "policy_content_hash": string;
  readonly "profile_revision": string;
  readonly "quote_identifier_id": string;
  readonly "reporting_basis": "us_gaap" | "ifrs";
  readonly "security_id": string;
  readonly "trend_revision": string;
};

export type SnapshotResponse = {
  readonly "compatibility_key": string;
  readonly "execution_id": string;
  readonly "generated_at": string;
  readonly "input_snapshot_id": string;
  readonly "outcome": "completed" | "completed_with_gaps";
  readonly "payload_hash": string;
  readonly "request_id": string;
  readonly "result": FundamentalsPayload;
  readonly "snapshot_id": string;
};

export type ValidationError = {
  readonly "ctx"?: Readonly<Record<string, unknown>>;
  readonly "input"?: unknown;
  readonly "loc": ReadonlyArray<string | number>;
  readonly "msg": string;
  readonly "type": string;
};

export type FundamentalsReadResult<T> =
  | { readonly status: 200; readonly data: T }
  | { readonly status: 404; readonly data: NoResult }
  | { readonly status: 422; readonly data: HTTPValidationError };
