// Generated by scripts/generate_valuation_api.py. Do not edit.

export type ApiError = {
  readonly "code": "not_found" | "conflict" | "invalid_request";
  readonly "message": "N/A";
};

export type AssumptionContent = {
  readonly "anchor_method": "explicit_carry_forward_annual_run_rate";
  readonly "anchor_source_index": number;
  readonly "author_id": string;
  readonly "authored_at": string;
  readonly "calendar": "calendar_year_equivalent";
  readonly "forecast_dates": ReadonlyArray<string>;
  readonly "judgments": ReadonlyArray<Judgment>;
  readonly "leap_day": "february_28";
  readonly "retrospective": boolean;
  readonly "scenarios": ReadonlyArray<Scenario>;
  readonly "sensitivities": ReadonlyArray<SensitivityGrid>;
  readonly "valuation_at": string;
};

export type AssumptionCreate = {
  readonly "content": AssumptionContent;
  readonly "idempotency_key": string;
  readonly "parent_id": string | null;
};

export type AssumptionSaved = {
  readonly "content": AssumptionContent;
  readonly "content_hash": string;
  readonly "id": string;
  readonly "parent_id": string | null;
};

export type BridgeResult = {
  readonly "adjustment": string | null;
  readonly "eligible": boolean;
  readonly "market_common_value": string | null;
  readonly "market_ev_target": string | null;
  readonly "reasons": ReadonlyArray<string>;
  readonly "shares": string | null;
};

export type Claim = {
  readonly "amount": string | null;
  readonly "as_of": string;
  readonly "basis": "economic_value" | "absence" | "unreviewed";
  readonly "captured_at": string;
  readonly "currency": string;
  readonly "economic_claim_ids": ReadonlyArray<string>;
  readonly "evidence_hash": string;
  readonly "fixture_url": string;
  readonly "kind": "cash" | "nonoperating_assets" | "debt" | "leases" | "preferred" | "nci" | "other";
  readonly "known_at": string;
  readonly "known_basis": "owner_reviewed_instant" | "date_only" | "unproven";
  readonly "reasons": ReadonlyArray<string>;
  readonly "state": "eligible_amount" | "evidenced_absence" | "unavailable";
};

export type Evaluation = {
  readonly "operating_ev": string;
  readonly "pv_explicit": string;
  readonly "pv_terminal": string;
  readonly "reasons": ReadonlyArray<string>;
  readonly "rows": ReadonlyArray<ForecastRow>;
  readonly "terminal_contribution": string | null;
  readonly "terminal_dominant": boolean | null;
  readonly "terminal_fcff": string;
  readonly "terminal_nopat": string;
  readonly "terminal_reinvestment": string;
  readonly "terminal_revenue": string;
  readonly "terminal_value": string;
};

export type ForecastRow = {
  readonly "cash_tax": string;
  readonly "ebit": string;
  readonly "fcff": string;
  readonly "nopat": string;
  readonly "pv": string;
  readonly "reinvestment": string;
  readonly "revenue": string;
  readonly "year": number;
};

export type HTTPValidationError = {
  readonly "detail"?: ReadonlyArray<ValidationError>;
};

export type Interval = {
  readonly "lower": string;
  readonly "upper": string;
};

export type Judgment = {
  readonly "effective_from": string;
  readonly "effective_to": string;
  readonly "parameter": string;
  readonly "rationale": string;
  readonly "supporting_hashes": ReadonlyArray<string>;
  readonly "unit": "fraction" | "currency" | "years" | "schedule" | "solver_policy";
};

export type LatestResponse = {
  readonly "latest_request_id": string;
  readonly "latest_request_state": string;
  readonly "run": RunResponse | null;
};

export type ModelDefinition = {
  readonly "bridge": "economic_claim_values_single_common_pool_no_dilution_v1";
  readonly "cash_tax": "tax_on_positive_ebit_no_nol_v1";
  readonly "engine_build": string;
  readonly "forecast": "nominal_annual_end_period_v1";
  readonly "lease_treatment": "operating_lease_capitalized_consistent_ebit_v1";
  readonly "numeric": "decimal80_half_even_interval_outward_v1";
  readonly "reinvestment": "net_capex_plus_change_noncash_operating_wc";
  readonly "revision": "reverse_fcff_operating_v1";
  readonly "solver": "decimal_interval_model_v1";
  readonly "terminal": "gordon_growth_roic_reinvestment_v1";
  readonly "terminal_domain": "0<=g<min(risk_free,wacc,roic);wacc>0;roic>0;margin>0;tax<1";
};

export type PriceEvidence = {
  readonly "action_basis": string;
  readonly "adjustment_basis": string | null;
  readonly "batch_id": string | null;
  readonly "currency": string | null;
  readonly "field": "close";
  readonly "observation_id": string | null;
  readonly "quote_identifier_id": string;
  readonly "reasons": ReadonlyArray<string>;
  readonly "reference_date": string;
  readonly "retrieval_cutoff": string;
  readonly "security_id": string;
  readonly "selection_hash": string;
  readonly "session_basis": string | null;
  readonly "source_id": string;
  readonly "source_known_at": string;
  readonly "usable": boolean;
  readonly "value": string | null;
};

export type ProofRegion = {
  readonly "derivative": Interval;
  readonly "disposition": "excluded" | "unique_root" | "unresolved";
  readonly "domain": Interval;
  readonly "left_residual": Interval | null;
  readonly "residual": Interval;
  readonly "right_residual": Interval | null;
  readonly "root": Interval | null;
};

export type RequestCreate = {
  readonly "idempotency_key": string;
  readonly "max_attempts": number;
  readonly "parent_request_id": string;
  readonly "review_id": string;
};

export type RequestResponse = {
  readonly "error_code": "worker_failure" | "cancelled" | "lease_expired" | "waiting_for_input" | "retry_scheduled" | "stage_blocked" | "stage_unsupported" | "stage_failed" | null;
  readonly "execution_id": string;
  readonly "request_id": string;
  readonly "run_id": string | null;
  readonly "stage_key": "valuation" | null;
  readonly "stage_state": "running" | "completed" | "blocked" | "unsupported" | "failed" | "cancelled" | null;
  readonly "state": "queued" | "running" | "waiting_for_input" | "retry_scheduled" | "completed" | "completed_with_gaps" | "failed" | "cancelled";
};

export type RunResponse = {
  readonly "compatibility_key": string;
  readonly "execution_id": string;
  readonly "generated_at": string;
  readonly "input_snapshot_id": string;
  readonly "outcome": "completed" | "completed_with_gaps";
  readonly "parent_run_id": string | null;
  readonly "payload_hash": string;
  readonly "request_id": string;
  readonly "result": ValuationPayload;
  readonly "run_id": string;
};

export type SafeAssumptions = {
  readonly "anchor_method": string;
  readonly "anchor_source_index": number;
  readonly "authored_at": string;
  readonly "calendar": string;
  readonly "content_hash": string;
  readonly "forecast_dates": ReadonlyArray<string>;
  readonly "leap_day": string;
  readonly "provenance": "explicit_user_judgment";
  readonly "retrospective": boolean;
  readonly "scenarios": ReadonlyArray<Scenario>;
};

export type Scenario = {
  readonly "growth": ReadonlyArray<string> | null;
  readonly "margins": ReadonlyArray<string> | null;
  readonly "name": string;
  readonly "reinvestment": ReadonlyArray<string> | null;
  readonly "revenue_anchor": string;
  readonly "risk_free": string;
  readonly "solve": SolveSpec;
  readonly "taxes": ReadonlyArray<string>;
  readonly "terminal_growth": string;
  readonly "terminal_margin": string | null;
  readonly "terminal_roic": string;
  readonly "terminal_tax": string;
  readonly "wacc": string;
};

export type ScenarioResult = {
  readonly "common_equity": string | null;
  readonly "conditional_per_share": string | null;
  readonly "evaluation": Evaluation | null;
  readonly "name": string;
  readonly "reasons": ReadonlyArray<string>;
  readonly "solve": SolveResult;
  readonly "solve_variable": "revenue_cagr" | "terminal_operating_margin" | "reinvestment_to_revenue";
  readonly "unit": "fraction";
};

export type SelectionKey = {
  readonly "as_of": string;
  readonly "captured_before": string;
  readonly "currency": string;
  readonly "engine_revision": string;
  readonly "evaluated_at": string;
  readonly "filed_cutoff": string | null;
  readonly "freshness_revision": string;
  readonly "history_mode": "as_filed_by_date" | "original_as_filed" | "latest_reported";
  readonly "history_revision": string;
  readonly "history_years": 3 | 5 | 10;
  readonly "issuer_id": string;
  readonly "period_basis": "annual" | "quarter" | "ttm" | "instant";
  readonly "period_end": string;
  readonly "period_start": string | null;
  readonly "policy_content_hash": string;
  readonly "profile_revision": string;
  readonly "quote_identifier_id": string;
  readonly "reporting_basis": "us_gaap" | "ifrs";
  readonly "security_id": string;
  readonly "trend_revision": string;
};

export type SensitivityCell = {
  readonly "common_equity": string | null;
  readonly "evaluation": Evaluation | null;
  readonly "reasons": ReadonlyArray<string>;
  readonly "solve": SolveResult | null;
  readonly "value": string | null;
  readonly "x": string;
  readonly "y": string;
};

export type SensitivityEffect = {
  readonly "elasticity": string | null;
  readonly "outputs": ReadonlyArray<string | null>;
  readonly "parameter": string;
  readonly "perturbations": ReadonlyArray<string>;
  readonly "rank": number | null;
  readonly "reasons": ReadonlyArray<string>;
};

export type SensitivityGrid = {
  readonly "conditional_parameter": string | null;
  readonly "name": string;
  readonly "output": "reverse_implied_parameter" | "conditional_reprice";
  readonly "reference_scenario": string;
  readonly "x_parameter": "wacc" | "terminal_growth" | "revenue_cagr" | "terminal_operating_margin" | "reinvestment_to_revenue";
  readonly "x_values": ReadonlyArray<string>;
  readonly "y_parameter": "wacc" | "terminal_growth" | "revenue_cagr" | "terminal_operating_margin" | "reinvestment_to_revenue";
  readonly "y_values": ReadonlyArray<string>;
};

export type SensitivityResult = {
  readonly "cells": ReadonlyArray<SensitivityCell>;
  readonly "effects": ReadonlyArray<SensitivityEffect>;
  readonly "name": string;
  readonly "output": "reverse_implied_parameter" | "conditional_reprice";
  readonly "request": SensitivityGrid;
  readonly "unit": "fraction" | "currency_per_share";
};

export type SharePool = {
  readonly "action_basis": string;
  readonly "as_of": string;
  readonly "captured_at": string;
  readonly "complete_action_coverage": boolean;
  readonly "complete_homogeneous_pool": boolean;
  readonly "currency": string;
  readonly "current_basic": string | null;
  readonly "current_diluted": string | null;
  readonly "evidence_hash": string;
  readonly "fixture_url": string;
  readonly "known_at": string;
  readonly "known_basis": "owner_reviewed_instant" | "date_only" | "unproven";
  readonly "no_crossholding_earnings_overlap": boolean;
  readonly "no_dilutive_claims": boolean;
  readonly "operating_lease_basis_matches": boolean;
  readonly "reasons": ReadonlyArray<string>;
  readonly "unrestricted_nonoperating_cash": boolean;
};

export type SolveResult = {
  readonly "evaluations": number;
  readonly "interval": Interval | null;
  readonly "iterations": number;
  readonly "proof": ReadonlyArray<ProofRegion>;
  readonly "proof_revision": "decimal_interval_model_v1";
  readonly "reasons": ReadonlyArray<string>;
  readonly "representative": string | null;
  readonly "residual": Interval | null;
  readonly "root_intervals": ReadonlyArray<Interval>;
  readonly "state": "converged" | "no_solution_in_domain" | "non_unique" | "inconclusive" | "unavailable";
  readonly "subdivisions": number;
  readonly "unresolved_domains": ReadonlyArray<Interval>;
};

export type SolveSpec = {
  readonly "absolute_tolerance": string;
  readonly "anchor_margin": string | null;
  readonly "lower": string;
  readonly "margin_weights": ReadonlyArray<string>;
  readonly "max_evaluations": number;
  readonly "max_iterations": number;
  readonly "max_subdivisions": number;
  readonly "relative_tolerance": string;
  readonly "upper": string;
  readonly "variable": "revenue_cagr" | "terminal_operating_margin" | "reinvestment_to_revenue";
  readonly "width_tolerance": string;
};

export type ValidationError = {
  readonly "ctx"?: Readonly<Record<string, unknown>>;
  readonly "input"?: unknown;
  readonly "loc": ReadonlyArray<string | number>;
  readonly "msg": string;
  readonly "type": string;
};

export type ValuationPayload = {
  readonly "assumptions": SafeAssumptions;
  readonly "bridge": BridgeResult;
  readonly "bridge_captured_before": string;
  readonly "claims": ReadonlyArray<Claim>;
  readonly "conclusions": ReadonlyArray<string>;
  readonly "currency": string;
  readonly "dependency_hash": string;
  readonly "evidence_mode": "synthetic";
  readonly "fixture_label": "Synthetic integration fixture \u2014 not company data";
  readonly "model": ModelDefinition;
  readonly "numerical_uncertainty": ReadonlyArray<readonly [string, ReadonlyArray<Interval>]>;
  readonly "policy": ValuationPolicy;
  readonly "price": PriceEvidence;
  readonly "reasons": ReadonlyArray<string>;
  readonly "scenario_dispersion": Interval | null;
  readonly "scenarios": ReadonlyArray<ScenarioResult>;
  readonly "sensitivities": ReadonlyArray<SensitivityResult>;
  readonly "shares": SharePool;
  readonly "source_eligibility_reasons": ReadonlyArray<string>;
  readonly "source_input_hash": string;
  readonly "source_measurement_uncertainty": ReadonlyArray<readonly [string, string | null]>;
  readonly "source_payload_hash": string;
  readonly "source_selector": SelectionKey;
  readonly "source_snapshot_id": string;
  readonly "valuation_at": string;
  readonly "version": "s7-result-v1";
};

export type ValuationPolicy = {
  readonly "applicability": "reviewed_operating_fcff" | "unsupported";
  readonly "applicability_evidence": string;
  readonly "effective_at": string;
  readonly "known_at": string;
  readonly "max_claim_age_days": number;
  readonly "max_financial_age_days": number;
  readonly "max_quote_age_days": number;
  readonly "revision": string;
  readonly "sensitivity_ranking": "absolute_symmetric_fraction_elasticity_v1";
  readonly "terminal_dominance_threshold": "0.75";
};

export type ValuationReadResult<T> =
  | { readonly status: 200; readonly data: T }
  | { readonly status: 404; readonly data: ApiError }
  | { readonly status: 422; readonly data: HTTPValidationError };
