"""Generate checked-in OpenAPI and TypeScript from the reviewed synthetic valuation API."""

import argparse
import json
from pathlib import Path
from typing import Any, NoReturn
from uuid import UUID

from equity_api.valuation import create_app

ROOT = Path(__file__).resolve().parents[1]


def no_database() -> NoReturn:
    raise RuntimeError("Contract generation must not connect to a database")


def ts_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return str(schema["$ref"]).rsplit("/", 1)[1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(item) for item in schema["enum"])
    if "anyOf" in schema or "oneOf" in schema:
        return " | ".join(ts_type(item) for item in schema.get("anyOf", schema.get("oneOf", [])))
    kind = schema.get("type")
    if kind in ("integer", "number"):
        return "number"
    if kind in ("string", "boolean", "null"):
        return str(kind)
    if kind == "array":
        if "prefixItems" in schema:
            return "readonly [" + ", ".join(ts_type(item) for item in schema["prefixItems"]) + "]"
        return "ReadonlyArray<" + ts_type(schema["items"]) + ">"
    if kind is None:
        return "unknown"
    if kind == "object":
        fields = []
        for name, item in sorted(schema.get("properties", {}).items()):
            optional = "" if name in schema.get("required", []) else "?"
            fields.append(f"  readonly {json.dumps(name)}{optional}: {ts_type(item)};")
        if "properties" not in schema and isinstance(schema.get("additionalProperties"), dict):
            return "Readonly<Record<string, " + ts_type(schema["additionalProperties"]) + ">>"
        if fields:
            return "{\n" + "\n".join(fields) + "\n}"
        return "Readonly<Record<string, unknown>>"
    raise ValueError(f"Unsupported JSON Schema shape: {schema}")


def outputs() -> dict[Path, str]:
    spec = create_app(workspace_id=UUID(int=0), connection_factory=no_database).openapi()
    text = "// Generated by scripts/generate_valuation_api.py. Do not edit.\n\n"
    for name, schema in sorted(spec["components"]["schemas"].items()):
        text += f"export type {name} = {ts_type(schema)};\n\n"
    text += (
        "export type ValuationReadResult<T> =\n"
        "  | { readonly status: 200; readonly data: T }\n"
        "  | { readonly status: 404; readonly data: ApiError }\n"
        "  | { readonly status: 422; readonly data: HTTPValidationError };\n"
    )
    return {
        ROOT / "packages/schema/openapi/valuation.json": json.dumps(
            spec, sort_keys=True, indent=2, ensure_ascii=False
        )
        + "\n",
        ROOT / "packages/schema/types/valuation.ts": text,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, text in outputs().items():
        if args.check:
            if not path.exists() or path.read_text() != text:
                print(f"Generated contract differs: {path.relative_to(ROOT)}")
                return 1
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
    print("S7a generated contracts match." if args.check else "S7a contracts generated.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
