"""Generate the TypeScript vocabulary from the reviewed Python enum."""

import argparse
from pathlib import Path

from equity_schema.concepts import Concept

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "packages/schema/types/concepts.ts"


def render() -> str:
    values = "\n".join(f'  "{member.value}",' for member in Concept)
    return (
        "// Generated by scripts/generate_concepts.py; do not edit.\n"
        f"export const CONCEPTS = [\n{values}\n] as const;\n"
        "export type Concept = (typeof CONCEPTS)[number];\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not TARGET.exists() or TARGET.read_text() != expected:
            print("Generated concepts are stale; run scripts/generate_concepts.py.")
            return 1
        print("Generated concept vocabulary matches Python.")
        return 0
    TARGET.write_text(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
