"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { DistributionChart, HistoryChart, ScatterChart } from "./charts";
import type { EvidenceDetail, SectorBundle, SectorRow } from "./types";

function SourceDrawer({ detail, onClose }: { detail: EvidenceDetail | undefined; onClose: () => void }) {
  const dialog = useRef<HTMLDialogElement>(null);
  useEffect(() => {
    if (detail && !dialog.current?.open) dialog.current?.showModal();
    if (!detail && dialog.current?.open) dialog.current.close();
  }, [detail]);
  return <dialog ref={dialog} className="source-drawer" onClose={onClose} aria-labelledby="source-title">
    {detail ? <><div className="drawer-heading"><span className="eyebrow">FROZEN SNAPSHOT · FICTIONAL</span><button className="icon-button" onClick={onClose} aria-label="Close source details">×</button></div><h2 id="source-title">{detail.title}</h2><p className="muted">{detail.subtitle}</p>
      {detail.sections.map((section) => <section key={section.heading} className="source-section"><h3>{section.heading}</h3><dl>{section.rows.map((row, index) => <div key={`${row.label}-${index}`}><dt>{row.label}</dt><dd>{row.value}</dd></div>)}</dl></section>)}
      <section className="source-section"><h3>Source chain</h3>{detail.sources.map((source, index) => <div className="source-item" key={`${source.label}-${index}`}><strong>{source.url ? <a href={source.url} target="_blank" rel="noreferrer">{source.label} ↗</a> : source.label}</strong>{source.accession ? <p>Accession · {source.accession}</p> : null}<p>Captured · {source.capturedAt}</p><p>Transform · {source.transform}</p><p>Usage · {source.licence}</p></div>)}</section></> : null}
  </dialog>;
}

export default function SectorExplorer({ bundle }: { bundle: SectorBundle }) {
  const [metricId, setMetricId] = useState("pe");
  const [method, setMethod] = useState("total");
  const [asOf, setAsOf] = useState(bundle.context.defaultAsOf);
  const [selectedSector, setSelectedSector] = useState(bundle.context.defaultSectorId);
  const [industryParent, setIndustryParent] = useState<string | null>(null);
  const [historySectors, setHistorySectors] = useState([bundle.context.defaultSectorId]);
  const [window, setWindow] = useState("3");
  const [sort, setSort] = useState<"alphabetical" | "numeric">("alphabetical");
  const [showMarket, setShowMarket] = useState(true);
  const [capSized, setCapSized] = useState(false);
  const [query, setQuery] = useState("");
  const [activeBin, setActiveBin] = useState<string | null>(null);
  const [pinnedCompany, setPinnedCompany] = useState<string | null>(null);
  const [detailId, setDetailId] = useState<string | null>(null);
  const view = bundle.views[`${asOf}|${metricId}|${method}`];
  const metric = bundle.metrics.find((item) => item.id === metricId);
  const methodEntry = bundle.methods.find((item) => item.id === method);
  const breadthMode = metricId.endsWith("_breadth");
  const methodLabel = breadthMode ? "Equal-company breadth" : methodEntry?.label;
  const sector = bundle.sectors.find((item) => item.id === selectedSector);
  const visibleSectors = bundle.sectors.filter((item) => industryParent ? item.parentId === industryParent : !item.parentId);
  const visibleIds = visibleSectors.map((item) => item.id);
  const distribution = view?.distributions[selectedSector];
  const activeBinData = distribution?.bins.find((bin) => bin.id === activeBin);
  const companies = distribution?.companies.filter((company) => (!activeBinData || activeBinData.companyIds.includes(company.id)) && `${company.name} ${company.ticker}`.toLowerCase().includes(query.toLowerCase())) ?? [];
  const rows = view ? view.orders[sort].map((id) => view.rows.find((row) => row.sectorId === id)).filter((row): row is SectorRow => Boolean(row && visibleIds.includes(row.sectorId))) : [];
  const history = view?.history[window];
  const selectedRow = view?.rows.find((row) => row.sectorId === selectedSector);
  const sectorLabel = (id: string) => bundle.sectors.find((item) => item.id === id)?.label ?? "Unclassified";
  const sectorColor = (id: string) => bundle.sectors.find((item) => item.id === id)?.color ?? "#768887";
  function describeDetail(id: string) {
    const detail = bundle.details[id];
    if (!detail) return "Source details unavailable";
    return [detail.title, ...detail.sections.filter((section) => /calculation|coverage|exclusion|history|comparison/i.test(section.heading)).flatMap((section) => section.rows.filter((row) => !/hash|cohort|snapshot/i.test(row.label)).map((row) => `${row.label}: ${row.value}`))].join("\n");
  }
  function changeSelection(action: () => void) { action(); setActiveBin(null); setDetailId(null); }
  function selectSector(id: string) { setSelectedSector(id); setHistorySectors([id]); setActiveBin(null); setPinnedCompany(null); setQuery(""); }
  function drillDown(id: string) {
    const child = bundle.sectors.find((item) => item.parentId === id);
    if (child) { setIndustryParent(id); selectSector(child.id); }
  }
  function toggleHistory(id: string) {
    setHistorySectors((current) => current.includes(id) ? current.filter((item) => item !== id) : current.length < 4 ? [...current, id] : current);
  }
  return <>
    <div className="fictional-banner"><strong>FICTIONAL DATA</strong><span>Development demonstration · invented companies · no market conclusions</span><Link href="/sectors">Production prerequisites ↗</Link></div>
    <header className="app-header"><Link href="/sectors" className="brand"><span className="brand-mark">E</span> EquityEval</Link><nav aria-label="Main"><span className="nav-active">Sector Explorer</span><Link href="/sectors">Data readiness</Link></nav><span className="local-indicator"><span /> Local workbench</span></header>
    <main className="explorer" data-snapshot-id={view?.id}>
      <div className="page-intro"><div><div className="eyebrow">THE BIG PICTURE, WITH THE DETAILS</div><h1>Sector Explorer<span className="title-dot">.</span></h1><p>See the sector. Understand the companies behind it.</p></div><div className="snapshot-stamp"><span className="eyebrow">SOURCE SNAPSHOT</span><code title={bundle.context.sourceSnapshotId}>{bundle.context.sourceSnapshotId.slice(0, 18)}</code><span>{bundle.context.membershipMode}</span></div></div>
      <section className="context-strip" aria-label="Pinned calculation context"><div><span>Universe</span><strong>{bundle.context.universe}</strong></div><div><span>Taxonomy</span><strong>{bundle.context.taxonomy}</strong></div><label><span>As of</span><select value={asOf} onChange={(event) => changeSelection(() => setAsOf(event.target.value))}>{bundle.context.asOfDates.map((date) => <option key={date}>{date}</option>)}</select></label><div><span>Period · currency</span><strong>{bundle.context.period} · {bundle.context.currency}</strong></div><div><span>Calculation</span><strong>{methodLabel}</strong></div></section>
      <section className="comparison-panel" aria-labelledby="comparison-title">
        <div className="panel-toolbar"><div className="metric-control"><label className="eyebrow" htmlFor="metric">MEASURE</label><select id="metric" value={metricId} onChange={(event) => changeSelection(() => { setMetricId(event.target.value); if (event.target.value.endsWith("_breadth")) setMethod("total"); })}>{bundle.metrics.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></div><div className="method-controls"><div className="segmented" aria-label="Calculation method">{bundle.methods.filter((item) => item.id !== "mean").map((item) => <button key={item.id} disabled={breadthMode} aria-pressed={method === item.id} onClick={() => changeSelection(() => setMethod(item.id))}>{breadthMode && item.id === "total" ? "Equal-company breadth" : item.label}</button>)}</div><details className="advanced-controls"><summary>Advanced</summary><button disabled={breadthMode} onClick={() => changeSelection(() => setMethod("mean"))} aria-pressed={method === "mean"}>Simple mean</button><p>Arithmetic mean of eligible company ratios. Extreme ratios can dominate; sample and the full distribution stay visible.</p></details></div></div>
        <div className="comparison-heading"><div><h2 id="comparison-title">{industryParent ? `${sectorLabel(industryParent)} industries` : "Across the selected sectors"}</h2><p>{view?.definition ?? metric?.definition}</p></div><div className="chart-controls"><label className="checkbox"><input type="checkbox" checked={showMarket} onChange={(event) => setShowMarket(event.target.checked)} /> Market reference</label><label className="sort-control">Sort <select value={sort} onChange={(event) => setSort(event.target.value as "alphabetical" | "numeric")}><option value="alphabetical">Alphabetical</option><option value="numeric">Value · eligible only</option></select></label></div></div>
        {method === "mean" ? <p className="method-warning">Simple mean · only eligible company ratios. It is sensitive to extreme values and is not a sector aggregate.</p> : null}
        {industryParent ? <button className="text-button back-link" onClick={() => { const parent = industryParent; setIndustryParent(null); selectSector(parent); }}>← All sectors</button> : null}
        {view ? <>
          <div className="bar-chart" aria-label={`${metric?.label}, ${methodLabel}, ${asOf}`}><div className="bar-column-head"><span>{industryParent ? "Industry" : "Sector"}</span><div className="bar-axis">{view.axis.ticks.map((tick) => <span key={`${tick.label}-${tick.position}`} style={{ left: `${tick.position}%` }}>{tick.label}</span>)}</div><span>Value</span><span>Data / cap coverage</span></div>
            {rows.map((row) => <div key={row.sectorId} className={`bar-row ${selectedSector === row.sectorId ? "is-selected" : ""}`}><button className="sector-label" onClick={() => selectSector(row.sectorId)} aria-pressed={selectedSector === row.sectorId}><span className="sector-swatch" style={{ background: sectorColor(row.sectorId) }} />{sectorLabel(row.sectorId)}<span className="row-arrow" aria-hidden="true">↗</span></button><div className="bar-track"><span className="bar-zero" style={{ left: `${view.axis.zero}%` }} />{showMarket && view.market?.bar && view.market.status === "eligible" ? <span className="market-marker" style={{ left: `${view.market.bar.endpoint}%` }} /> : null}{row.bar ? <button className={`sector-bar ${row.status === "limited" ? "limited-bar" : ""}`} style={{ left: `${row.bar.left}%`, width: `${row.bar.width}%`, backgroundColor: sectorColor(row.sectorId), borderColor: sectorColor(row.sectorId) }} title={describeDetail(row.detailId)} onClick={() => setDetailId(row.detailId)} aria-label={`${sectorLabel(row.sectorId)} ${row.valueLabel}, ${row.statusLabel}. Source details.`}><span className="sr-only">{row.valueLabel}</span></button> : <span className="missing-bar-label">{row.statusLabel}</span>}</div><button className="bar-value text-button" title={describeDetail(row.detailId)} onClick={() => setDetailId(row.detailId)}>{row.valueLabel}{row.status === "limited" ? <span>Limited coverage</span> : null}</button><button className="coverage-cell text-button" title={describeDetail(row.detailId)} onClick={() => setDetailId(row.detailId)}><strong>{row.coverageLabel} <span>/ {row.capCoverageLabel}</span></strong><span>{row.countsLabel}</span></button></div>)}
          </div>
          <div className="comparison-footnote"><span>Outlined bars = limited coverage. Missing and N/M rows remain visible.</span>{showMarket && view.market ? <button className="text-button market-key" title={describeDetail(view.market.detailId)} onClick={() => setDetailId(view.market!.detailId)}>{view.market.status === "eligible" ? <i /> : null}<span>{`Market reference — eligible companies · ${view.market.valueLabel} · ${view.market.statusLabel} · data ${view.market.coverageLabel} / cap ${view.market.capCoverageLabel}`}</span></button> : null}</div>
          <details className="data-table"><summary>Comparison data, exclusions & methods</summary><div className="table-scroll"><table><caption>{metric?.label} · {methodLabel} · {asOf}</caption><thead><tr><th>Sector</th><th>Value</th><th>Counts</th><th>Data coverage</th><th>Cap coverage</th><th>Status / exclusions</th></tr></thead><tbody>{rows.map((row) => <tr key={row.sectorId}><td>{sectorLabel(row.sectorId)}</td><td><button className="text-button" onClick={() => setDetailId(row.detailId)}>{row.valueLabel}</button></td><td>{row.countsLabel}<br />{row.eligibilityLabel}</td><td>{row.coverageLabel}</td><td>{row.capCoverageLabel}</td><td>{row.statusLabel}; {row.reasons.join(", ") || "None"}</td></tr>)}</tbody></table></div></details>
        </> : <div className="empty-chart">No saved snapshot matches this selection. No previous values are carried forward.</div>}
      </section>
      {view && sector ? <>
        <div className="section-heading"><div><div className="eyebrow">LOOK INSIDE</div><h2><span className="sector-swatch" style={{ background: sector.color }} />{sector.label}</h2></div><div className="section-actions">{bundle.sectors.some((item) => item.parentId === sector.id) ? <button className="secondary-button" onClick={() => drillDown(sector.id)}>Explore industries ↗</button> : null}{selectedRow ? <button className="secondary-button" onClick={() => setDetailId(selectedRow.detailId)}>Coverage & calculation</button> : null}</div></div>
        {selectedRow?.observations?.length ? <div className="growth-observations">{selectedRow.observations.map((observation) => <p key={observation}>{observation}</p>)}</div> : null}
        {selectedRow?.concentration ? <div className="concentration-strip"><button onClick={() => setDetailId(selectedRow.detailId)}><span>Current top-five cap share</span><strong>{selectedRow.concentration.currentShareLabel}</strong><small>{selectedRow.concentration.currentDate}</small></button><button onClick={() => setDetailId(selectedRow.detailId)}><span>Revenue growth excluding prior top five</span><strong>{selectedRow.concentration.growthLabel}</strong><small>Leader set fixed at {selectedRow.concentration.priorDate ?? "unavailable date"}</small></button><p>{selectedRow.concentration.reasons.join(" · ") || "Same issuer cohort in both revenue periods. Current concentration and prior leaders have separate dates."}</p></div> : null}
        <div className="research-grid"><section className="chart-panel"><div className="panel-heading"><div><span className="eyebrow">01 / THROUGH TIME</span><h3>{metric?.label} history</h3></div><div className="segmented compact" aria-label="History window">{["1", "3", "5"].map((years) => <button key={years} aria-pressed={window === years} onClick={() => setWindow(years)}>{years}Y</button>)}</div></div><div className="history-selectors" aria-label="Select up to four sectors for history">{visibleSectors.map((item) => <label key={item.id} className="checkbox"><input type="checkbox" checked={historySectors.includes(item.id)} disabled={!historySectors.includes(item.id) && historySectors.length >= 4} onChange={() => toggleHistory(item.id)} /><i style={{ background: item.color }} />{item.label}</label>)}</div><p className="small muted">{methodLabel} · {bundle.context.period} · up to four sectors</p>{history ? <HistoryChart data={history} sectors={bundle.sectors} selected={historySectors} describeDetail={describeDetail} onDetail={setDetailId} /> : <div className="empty-chart">No historical snapshot available.</div>}</section>
          <section className="chart-panel"><div className="panel-heading"><div><span className="eyebrow">02 / WITHIN THE SECTOR</span><h3>Company distribution</h3></div><span className="quiet-label">{metric?.label}</span></div><p className="small muted">Eligible company values · {asOf} · every outlier retained</p>{distribution ? <DistributionChart data={distribution} activeBin={activeBin} pinnedCompany={pinnedCompany} onBin={setActiveBin} describeDetail={describeDetail} onDetail={setDetailId} /> : <div className="empty-chart">No eligible distribution available.</div>}</section>
          <section className="chart-panel scatter-panel"><div className="panel-heading"><div><span className="eyebrow">03 / TWO DIFFERENT QUESTIONS</span><h3>Growth versus valuation</h3></div><label className="checkbox"><input type="checkbox" checked={capSized} onChange={(event) => setCapSized(event.target.checked)} /> Size by market cap</label></div><p className="small muted">Both axes: {methodEntry?.label}. Growth and valuation are observations, not an investment ranking.</p><ScatterChart data={{ ...view.scatter, points: view.scatter.points.filter((point) => visibleIds.includes(point.sectorId)), unavailable: view.scatter.unavailable.filter((item) => visibleIds.includes(item.sectorId)) }} sectors={bundle.sectors} sized={capSized} selected={selectedSector} onSelect={selectSector} describeDetail={describeDetail} onDetail={setDetailId} /><p className="research-prompt">What might explain the difference? Research growth persistence, margins, business mix and risk.</p></section>
          <aside className="reading-panel"><span className="eyebrow">HOW TO READ THIS VIEW</span><h3>One sector.<br />Different perspectives.</h3><div><span className="reading-number">01</span><p><strong>Sector total</strong> combines matching numerator and denominator amounts. Losses stay in aggregate earnings.</p></div><div><span className="reading-number">02</span><p><strong>Typical company</strong> is the median eligible company. Median P/E describes profitable companies only.</p></div><div><span className="reading-number">03</span><p><strong>Coverage changes the comparison.</strong> N is the roster, K has complete inputs and V contributes to the selected method.</p></div><p className="small muted">Sector fundamentals do not directly measure an ETF’s return. Its membership, weights, fees and concentration may differ.</p><details><summary>Missing production prerequisites</summary><ul>{bundle.context.prerequisites.map((item) => <li key={item}>{item}</li>)}</ul></details></aside>
        </div>
        <section className="constituents-panel" aria-labelledby="constituent-title"><div className="panel-heading"><div><span className="eyebrow">THE COMPANIES BEHIND THE GRAPH</span><h3 id="constituent-title">{sector.label} constituents</h3></div><label className="search-field"><span className="sr-only">Search companies</span><span aria-hidden="true">⌕</span><input type="search" placeholder="Find a company or ticker" value={query} onChange={(event) => setQuery(event.target.value)} /></label></div>{activeBinData ? <div className="filter-chip">Bin: {activeBinData.label}<button aria-label="Clear histogram filter" onClick={() => setActiveBin(null)}>×</button></div> : null}<div className="table-scroll"><table><caption className="sr-only">Frozen company fundamentals for {sector.label}</caption><thead><tr><th>Company</th><th>{metric?.label}</th><th>Eligibility</th><th>Distribution</th><th>Snapshot</th></tr></thead><tbody>{companies.map((company) => <tr key={company.id} data-snapshot-id={company.snapshotId}><td><strong>{company.ticker}</strong><span className="company-name">{company.name}</span></td><td><button className="text-button" onClick={() => setDetailId(company.detailId)}>{company.valueLabel}</button></td><td><span className={`status-label ${company.status === "eligible" ? "status-eligible" : ""}`}>{company.status}</span><span className="company-reason">{company.reasons.join(", ")}</span></td><td><button className="text-button" aria-pressed={pinnedCompany === company.id} onClick={() => setPinnedCompany(pinnedCompany === company.id ? null : company.id)}>{pinnedCompany === company.id ? "Unpin" : "Pin company"}</button></td><td><button className="text-button" title={company.snapshotId} onClick={() => setDetailId(company.detailId)}>Fundamentals ↗</button></td></tr>)}</tbody></table>{companies.length === 0 ? <p className="empty-table">No companies match this filter. <button className="text-button" onClick={() => { setQuery(""); setActiveBin(null); }}>Clear filters</button></p> : null}</div></section>
      </> : null}
      <footer className="explorer-footer"><span>FICTIONAL SNAPSHOT · {asOf} · {bundle.context.period} · {bundle.context.currency}</span><span>{bundle.context.rulesVersion} / {bundle.context.policyVersion}</span></footer>
    </main><SourceDrawer detail={detailId ? bundle.details[detailId] : undefined} onClose={() => setDetailId(null)} />
  </>;
}
