"use client";

import Link from "next/link";
import { useState } from "react";
import WorkbenchShell from "@/components/WorkbenchShell";
import EvidenceDrawer from "@/components/EvidenceDrawer";
import { DistributionChart, HistoryChart, ScatterChart, historyLinePattern } from "./charts";
import type { SectorBundle, SectorRow } from "./types";


export default function SectorExplorer({ bundle }: { bundle: SectorBundle }) {
  const [metricId, setMetricId] = useState("pe");
  const [method, setMethod] = useState("total");
  const [asOf, setAsOf] = useState(bundle.context.defaultAsOf);
  const [selectedSector, setSelectedSector] = useState(bundle.context.defaultSectorId);
  const [industryParent, setIndustryParent] = useState<string | null>(null);
  const [historySelection, setHistorySelection] = useState([{ id: bundle.context.defaultSectorId, slot: 0 }]);
  const historySectors = historySelection.map((item) => item.id);
  const historySlots = Object.fromEntries(historySelection.map((item) => [item.id, item.slot]));
  const [window, setWindow] = useState("3");
  const [sort, setSort] = useState<"alphabetical" | "numeric">("alphabetical");
  const [showMarket, setShowMarket] = useState(true);
  const [capSized, setCapSized] = useState(false);
  const [query, setQuery] = useState("");
  const [activeBin, setActiveBin] = useState<string | null>(null);
  const [pinnedCompany, setPinnedCompany] = useState<string | null>(null);
  const [detailId, setDetailId] = useState<string | null>(null);
  const view = bundle.views[`${asOf}|${metricId}|${method}`];
  const metric = bundle.metrics.find((item) => item.id === metricId);
  const methodEntry = bundle.methods.find((item) => item.id === method);
  const breadthMode = metricId.endsWith("_breadth");
  const methodLabel = breadthMode ? "Equal-company breadth" : methodEntry?.label;
  const sector = bundle.sectors.find((item) => item.id === selectedSector);
  const visibleSectors = bundle.sectors.filter((item) => industryParent ? item.parentId === industryParent : !item.parentId);
  const visibleIds = visibleSectors.map((item) => item.id);
  const distribution = view?.distributions[selectedSector];
  const activeBinData = distribution?.bins.find((bin) => bin.id === activeBin);
  const companies = distribution?.companies.filter((company) => (!activeBinData || activeBinData.companyIds.includes(company.id)) && `${company.name} ${company.ticker}`.toLowerCase().includes(query.toLowerCase())) ?? [];
  const rows = view ? view.orders[sort].map((id) => view.rows.find((row) => row.sectorId === id)).filter((row): row is SectorRow => Boolean(row && visibleIds.includes(row.sectorId))) : [];
  const history = view?.history[window];
  const selectedRow = view?.rows.find((row) => row.sectorId === selectedSector);
  const sectorLabel = (id: string) => bundle.sectors.find((item) => item.id === id)?.label ?? "Unclassified";
  function describeDetail(id: string) {
    const detail = bundle.details[id];
    if (!detail) return "Source details unavailable";
    return [detail.title, ...detail.sections.filter((section) => /calculation|coverage|exclusion|history|comparison/i.test(section.heading)).flatMap((section) => section.rows.filter((row) => !/hash|cohort|snapshot/i.test(row.label)).map((row) => `${row.label}: ${row.value}`))].join("\n");
  }
  function changeSelection(action: () => void) { action(); setActiveBin(null); setDetailId(null); }
  function selectSector(id: string) { setSelectedSector(id); setHistorySelection([{ id, slot: 0 }]); setActiveBin(null); setPinnedCompany(null); setQuery(""); }
  function drillDown(id: string) {
    const child = bundle.sectors.find((item) => item.parentId === id);
    if (child) { setIndustryParent(id); selectSector(child.id); }
  }
  function toggleHistory(id: string) {
    setHistorySelection((current) => {
      if (current.some((item) => item.id === id)) return current.filter((item) => item.id !== id);
      const slot = [0, 1, 2, 3].find((value) => !current.some((item) => item.slot === value));
      return slot === undefined ? current : [...current, { id, slot }];
    });
  }
  return <WorkbenchShell active="sectors" fictional>
    <main id="main-content" tabIndex={-1} className="explorer" data-snapshot-id={view?.id}>
      <div className="page-intro"><div><div className="eyebrow">THE BIG PICTURE, WITH THE DETAILS</div><h1>Sector Explorer</h1><p>See the sector, then the companies behind it. Inspect the evidence behind every result.</p></div><div className="snapshot-stamp"><span className="eyebrow">SOURCE SNAPSHOT</span><code title={bundle.context.sourceSnapshotId}>{bundle.context.sourceSnapshotId.slice(0, 18)}</code><span>{bundle.context.membershipMode}</span></div></div>
      <section className="context-strip" aria-label="Pinned calculation context"><div><span>Universe</span><strong>{bundle.context.universe}</strong></div><div><span>Taxonomy</span><strong>{bundle.context.taxonomy}</strong></div><label><span>Evaluation date</span><select value={asOf} onChange={(event) => changeSelection(() => setAsOf(event.target.value))}>{bundle.context.asOfDates.map((date) => <option key={date}>{date}</option>)}</select></label><div><span>Period · currency</span><strong>{bundle.context.period} · {bundle.context.currency}</strong></div><div><span>Calculation</span><strong>{methodLabel}</strong></div></section>
      <section className="comparison-panel" aria-labelledby="comparison-title">
        <div className="panel-toolbar"><div className="metric-control"><label className="eyebrow" htmlFor="metric">MEASURE</label><select id="metric" value={metricId} onChange={(event) => changeSelection(() => { setMetricId(event.target.value); if (event.target.value.endsWith("_breadth")) setMethod("total"); })}>{bundle.metrics.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></div><div className="method-controls"><div className="segmented" aria-label="Calculation method">{bundle.methods.filter((item) => item.id !== "mean").map((item) => <button key={item.id} disabled={breadthMode && item.id !== "total"} aria-pressed={method === item.id} onClick={() => changeSelection(() => setMethod(item.id))}>{breadthMode && item.id === "total" ? "Equal-company breadth" : item.label}</button>)}</div><details className="advanced-controls"><summary>Advanced method</summary><div className="advanced-popover"><button disabled={breadthMode} onClick={() => changeSelection(() => setMethod("mean"))} aria-pressed={method === "mean"}>Simple mean</button><p>Arithmetic mean of eligible company ratios. Extreme ratios can dominate; sample and the full distribution stay visible.</p></div></details></div></div>
        <div className="comparison-heading"><div><h2 id="comparison-title">{industryParent ? `${sectorLabel(industryParent)} industries` : "Across the declared sectors"}</h2><p>{view?.definition ?? metric?.definition}</p></div><div className="chart-controls"><label className="checkbox"><input type="checkbox" checked={showMarket} onChange={(event) => setShowMarket(event.target.checked)} /> Market reference</label><label className="sort-control">Sort <select value={sort} onChange={(event) => setSort(event.target.value as "alphabetical" | "numeric")}><option value="alphabetical">Alphabetical</option><option value="numeric">Value · eligible only</option></select></label></div></div>
        {method === "mean" ? <p className="method-warning">Simple mean · only eligible company ratios. It is sensitive to extreme values and is not a sector aggregate.</p> : null}
        {industryParent ? <button className="text-button back-link" onClick={() => { const parent = industryParent; setIndustryParent(null); selectSector(parent); }}>← All sectors</button> : null}
        {view ? <>
          <div className="bar-chart" aria-label={`${metric?.label}, ${methodLabel}, ${asOf}`}><div className="bar-column-head"><span>{industryParent ? "Industry" : "Sector"}</span><div className="bar-axis">{view.axis.ticks.map((tick) => <span key={`${tick.label}-${tick.position}`} style={{ left: `${tick.position}%` }}>{tick.label}</span>)}</div><span>Value</span><span>N · K · V · coverage</span></div>
            {rows.map((row) => <div key={row.sectorId} className={`bar-row ${selectedSector === row.sectorId ? "is-selected" : ""}`}><button className="sector-label" onClick={() => selectSector(row.sectorId)} aria-pressed={selectedSector === row.sectorId}><span className="sector-swatch" style={{ background: "var(--accent)" }} />{sectorLabel(row.sectorId)}<span className="row-arrow" aria-hidden="true">↗</span></button><div className="bar-track"><span className="bar-zero" style={{ left: `${view.axis.zero}%` }} />{showMarket && view.market?.bar && view.market.status === "eligible" ? <span className="market-marker" style={{ left: `${view.market.bar.endpoint}%` }} /> : null}{row.bar ? <button className={`sector-bar ${row.status === "limited" ? "limited-bar" : ""}`} style={{ left: `${row.bar.left}%`, width: `${row.bar.width}%`, backgroundColor: "var(--accent)", borderColor: "var(--accent)" }} title={describeDetail(row.detailId)} onClick={() => setDetailId(row.detailId)} aria-label={`${sectorLabel(row.sectorId)} ${row.valueLabel}, ${row.statusLabel}. Source details.`}><span className="sr-only">{row.valueLabel}</span></button> : <span className="missing-bar-label">{row.statusLabel}</span>}</div><button className="bar-value text-button" title={describeDetail(row.detailId)} onClick={() => setDetailId(row.detailId)}>{row.valueLabel}{row.status === "limited" ? <span>Limited coverage</span> : null}</button><button className="coverage-cell text-button" title={describeDetail(row.detailId)} onClick={() => setDetailId(row.detailId)}><strong>{row.countsLabel}</strong><span>Data {row.coverageLabel} · cap {row.capCoverageLabel}</span></button></div>)}
          </div>
          <details className="coverage-legend"><summary>How to read coverage · N, K and V</summary><p><strong>N</strong> is the complete roster. <strong>K</strong> has the required matching inputs. <strong>V</strong> contributes to this metric and calculation method. Known losses stay in aggregate earnings; an N/M company multiple is excluded from the median.</p><p>This demonstration compares only results passing its versioned policy: at least 10 contributors, 70% input coverage and 80% capitalization coverage. Unknown cap coverage fails the gate. Open a result for its exact exclusions and calculation.</p></details>
          <div className="comparison-footnote"><span className="encoding-legend"><i aria-hidden="true" /> Outlined bars = limited coverage. Missing and N/M rows remain visible.</span></div>
          {showMarket && view.market ? <button className="market-reference" data-status={view.market.status} title={describeDetail(view.market.detailId)} onClick={() => setDetailId(view.market!.detailId)}><span className="market-key">{view.market.status === "eligible" ? <i aria-hidden="true" /> : null}Market reference · {methodLabel} · {view.market.valueLabel}</span><span className="market-status">{view.market.statusLabel}{view.market.status !== "eligible" ? " — no dashed reference line is drawn" : " — dashed line in the chart"} · data {view.market.coverageLabel} · cap {view.market.capCoverageLabel}</span><span className="small">Inspect the matching universe, coverage and evidence ↗</span></button> : null}
          <details className="data-table"><summary>Comparison data, exclusions & methods</summary><div className="table-scroll"><table><caption>{metric?.label} · {methodLabel} · {asOf}</caption><thead><tr><th>Sector</th><th>Value</th><th>Counts</th><th>Data coverage</th><th>Cap coverage</th><th>Status / exclusions</th></tr></thead><tbody>{rows.map((row) => <tr key={row.sectorId}><td>{sectorLabel(row.sectorId)}</td><td><button className="text-button" onClick={() => setDetailId(row.detailId)}>{row.valueLabel}</button></td><td>{row.countsLabel}<br />{row.eligibilityLabel}</td><td>{row.coverageLabel}</td><td>{row.capCoverageLabel}</td><td>{row.statusLabel}; {row.reasons.join(", ") || "None"}</td></tr>)}</tbody></table></div></details>
        </> : <div className="empty-chart">No saved snapshot matches this selection. No previous values are carried forward.</div>}
      </section>
      {view && sector ? <>
        <div className="section-heading"><div><div className="eyebrow">LOOK INSIDE</div><h2><span className="sector-swatch" style={{ background: "var(--accent)" }} />{sector.label}</h2></div><div className="section-actions">{bundle.sectors.some((item) => item.parentId === sector.id) ? <button className="secondary-button" onClick={() => drillDown(sector.id)}>Explore industries ↗</button> : null}{selectedRow ? <button className="secondary-button" onClick={() => setDetailId(selectedRow.detailId)}>Coverage & calculation</button> : null}</div></div>
        {selectedRow?.observations?.length ? <div className="growth-observations">{selectedRow.observations.map((observation) => <p key={observation}>{observation}</p>)}</div> : null}
        {selectedRow?.concentration ? <div className="concentration-strip"><button onClick={() => setDetailId(selectedRow.detailId)}><span>Current top-five cap share</span><strong>{selectedRow.concentration.currentShareLabel}</strong><small>{selectedRow.concentration.currentDate}</small></button><button onClick={() => setDetailId(selectedRow.detailId)}><span>Revenue growth excluding prior top five</span><strong>{selectedRow.concentration.growthLabel}</strong><small>Leader set fixed at {selectedRow.concentration.priorDate ?? "unavailable date"}</small></button><p>{selectedRow.concentration.reasons.join(" · ") || "Same issuer cohort in both revenue periods. Current concentration and prior leaders have separate dates."}</p></div> : null}
        <div className="research-grid"><section className="chart-panel"><div className="panel-heading"><div><span className="eyebrow">01 / THROUGH TIME</span><h3>{metric?.label} history</h3></div><div className="segmented compact" aria-label="History window">{["1", "3", "5"].map((years) => <button key={years} aria-pressed={window === years} onClick={() => setWindow(years)}>{years}Y</button>)}</div></div><div className="history-selectors" aria-label="Select up to four sectors for history">{visibleSectors.map((item) => <label key={item.id} className="checkbox"><input type="checkbox" checked={historySectors.includes(item.id)} disabled={!historySectors.includes(item.id) && historySectors.length >= 4} onChange={() => toggleHistory(item.id)} /><svg className="history-series-key" width="24" height="10" viewBox="0 0 24 10" aria-hidden="true"><line className="history-line-pattern" x1="0" x2="24" y1="5" y2="5" strokeWidth="2" strokeDasharray={historyLinePattern(historySlots[item.id])} /></svg>{item.label}</label>)}</div><p className="small muted">{methodLabel} · {bundle.context.period} · up to four sectors</p>{history ? <HistoryChart data={history} sectors={bundle.sectors} selected={historySectors} slots={historySlots} describeDetail={describeDetail} onDetail={setDetailId} /> : <div className="empty-chart">No historical snapshot available.</div>}</section>
          <section className="chart-panel"><div className="panel-heading"><div><span className="eyebrow">02 / WITHIN THE SECTOR</span><h3>Company distribution</h3></div><span className="quiet-label">{metric?.label}</span></div><p className="small muted">Eligible company values · {asOf} · every outlier retained</p>{distribution ? <DistributionChart data={distribution} activeBin={activeBin} pinnedCompany={pinnedCompany} onBin={setActiveBin} describeDetail={describeDetail} onDetail={setDetailId} /> : <div className="empty-chart">No eligible distribution available.</div>}</section>
          <section className="chart-panel scatter-panel"><div className="panel-heading"><div><span className="eyebrow">03 / TWO DIFFERENT QUESTIONS</span><h3>Growth versus valuation</h3></div><label className="checkbox"><input type="checkbox" checked={capSized} onChange={(event) => setCapSized(event.target.checked)} /> Size by market cap</label></div><p className="small muted">Both axes: {methodEntry?.label}. Growth and valuation are observations, not an investment ranking.</p><ScatterChart data={{ ...view.scatter, points: view.scatter.points.filter((point) => visibleIds.includes(point.sectorId)), unavailable: view.scatter.unavailable.filter((item) => visibleIds.includes(item.sectorId)) }} sectors={bundle.sectors} sized={capSized} selected={selectedSector} onSelect={selectSector} describeDetail={describeDetail} onDetail={setDetailId} /><p className="research-prompt">What might explain the difference? Research growth persistence, margins, business mix and risk.</p></section>
          <aside className="reading-panel"><span className="eyebrow">HOW TO READ THIS VIEW</span><h3>One sector.<br />Different perspectives.</h3><div><span className="reading-number">01</span><p><strong>Sector total</strong> combines matching numerator and denominator amounts. Losses stay in aggregate earnings.</p></div><div><span className="reading-number">02</span><p><strong>Typical company</strong> is the median eligible company. Median P/E describes profitable companies only.</p></div><div><span className="reading-number">03</span><p><strong>Coverage changes the comparison.</strong> N is the roster, K has complete inputs and V contributes to the selected method.</p></div><p className="small muted">Sector fundamentals do not directly measure an ETF’s return. Its membership, weights, fees and concentration may differ.</p><details><summary>Missing production prerequisites</summary><ul>{bundle.context.prerequisites.map((item) => <li key={item}>{item}</li>)}</ul></details></aside>
        </div>
        <section className="constituents-panel" aria-labelledby="constituent-title"><div className="panel-heading"><div><span className="eyebrow">THE COMPANIES BEHIND THE GRAPH</span><h3 id="constituent-title">{sector.label} constituents</h3></div><label className="search-field"><span className="sr-only">Search companies</span><span aria-hidden="true">⌕</span><input type="search" placeholder="Find a company or ticker" value={query} onChange={(event) => setQuery(event.target.value)} /></label></div>{activeBinData ? <div className="filter-chip">Bin: {activeBinData.label}<button aria-label="Clear histogram filter" onClick={() => setActiveBin(null)}>×</button></div> : null}<div className="table-scroll"><table><caption className="sr-only">Frozen company fundamentals for {sector.label}</caption><thead><tr><th>Company</th><th>{metric?.label}</th><th>Eligibility</th><th>Distribution</th><th>Snapshot</th></tr></thead><tbody>{companies.map((company) => <tr key={company.id} className={pinnedCompany === company.id ? "pinned-company" : undefined} data-snapshot-id={company.snapshotId}><td><strong>{company.ticker}</strong><span className="company-name">{company.name}</span></td><td><button className="text-button" onClick={() => setDetailId(company.detailId)}>{company.valueLabel}</button></td><td><span className={`status-label ${company.status === "eligible" ? "status-eligible" : ""}`}>{company.status}</span><span className="company-reason">{company.reasons.join(", ")}</span></td><td><button className="text-button" aria-pressed={pinnedCompany === company.id} onClick={() => setPinnedCompany(pinnedCompany === company.id ? null : company.id)}>{pinnedCompany === company.id ? "Unpin" : "Pin company"}</button></td><td><Link title={company.snapshotId} href={`/development/company?company=${encodeURIComponent(company.id)}&asOf=${encodeURIComponent(asOf)}`}>Fundamentals ↗</Link></td></tr>)}</tbody></table>{companies.length === 0 ? <p className="empty-table">No companies match this filter. <button className="text-button" onClick={() => { setQuery(""); setActiveBin(null); }}>Clear filters</button></p> : null}</div></section>
      </> : null}
      <section id="research-roadmap" className="roadmap-panel" aria-labelledby="roadmap-title"><div className="panel-heading"><div><span className="eyebrow">RESEARCH WORKSPACE</span><h2 id="roadmap-title">Continue your research</h2></div><span className="scope-tag">Planned</span></div><p>The graphs above use frozen fictional results. Company fundamentals, Help and the News workspace are available as development views. Live analysis, saved theses and monitoring remain planned.</p><ul className="roadmap-list"><li><strong><Link href="/development/company">Company fundamentals ↗</Link></strong><span>Open sourced metrics and 3 / 5 / 10-year windows. Two fictional company snapshots are available; missing inputs remain visible.</span></li><li><strong>Business profile & change explanations</strong><span>Versioned business, lifecycle and instrument context. Separate numerical changes from possible business causes.</span></li><li><strong>Expectations & earnings review</strong><span>Save reasoning, evidence and dated falsification conditions. Compare later evidence, then retain, revise or retire the expectation.</span></li><li><strong>Watchlist & full reanalysis</strong><span>Add an exact security, follow each stage and revisit preserved analysis versions. Initial pilot: CRCL, MSTR, COIN, HOOD, USAR, MP, GOOGL.</span></li><li><strong><Link href="/development/news">News & economic calendar ↗</Link></strong><span>Explore proposed stock topics, macro scope and service readiness. Separate collection and assessment health; in-app, desktop and email delivery remain unconfigured.</span></li><li><strong><Link href="/help">Help & further research ↗</Link></strong><span>Read the development guide and searchable glossary. Valuation models, scenarios, catalysts, thesis history and calibration retain their planned scope.</span></li></ul></section>
      <footer className="explorer-footer"><span>FICTIONAL SNAPSHOT · {asOf} · {bundle.context.period} · {bundle.context.currency}</span><span>{bundle.context.rulesVersion} / {bundle.context.policyVersion}</span></footer>
    </main><EvidenceDrawer detail={detailId ? bundle.details[detailId] : undefined} onClose={() => setDetailId(null)} />
  </WorkbenchShell>;
}
