import type { Metadata } from "next";
import Link from "next/link";
import WorkbenchShell from "@/components/WorkbenchShell";
import Glossary, { type GlossaryEntry } from "@/features/help/Glossary";
import styles from "@/features/help/help.module.css";

export const metadata: Metadata = {
  title: "Help & terminology · EquityEval",
  description: "A practical guide to EquityEval's development views, evidence, coverage, history and financial terminology.",
};

const glossary: readonly GlossaryEntry[] = [
  { id: "returns", term: "ROA · ROE · ROIC", category: "Fundamentals", definition: "Return on assets, return on equity and return on invested capital relate a compatible income measure to the capital supporting it. They answer different questions and are not interchangeable.", detail: "Check the numerator scope, dated opening and closing balances, averaging method and invested-capital convention. These measures are unavailable in the Company demonstration because the required inputs are not supplied. A negative or tiny capital base can make a ratio unsuitable for comparison." },
  { id: "ticker", term: "Ticker · issuer · CIK · security", category: "Identity", definition: "A ticker is a trading symbol; an issuer is the reporting company; its CIK is its SEC identifier. A security is a particular instrument issued by that company.", detail: "Symbols can change or be reused. Check the exchange, currency and share class before comparing prices, earnings or share counts." },
  { id: "ads", term: "Ordinary share · ADS", category: "Identity", definition: "An American depositary share represents underlying shares under specified terms. It is a different instrument from an ordinary share.", detail: "An ADS price and an ordinary-share earnings figure cannot be combined without a reviewed conversion and matching dates." },
  { id: "profile", term: "Business profile · lifecycle", category: "Research · planned", definition: "A dated description of how a company or segment makes money, its development stage and its instrument. It determines which comparisons and models are suitable.", detail: "The planned profile is evidenced and versioned, not a universal sector score. A company can combine an operating segment and a development project; changing its profile must preserve older analyses." },
  { id: "annual", term: "Annual · fiscal year", category: "Periods", definition: "A financial flow covering a full reporting year. A fiscal year need not end in December.", detail: "Revenue is measured over an interval; cash is measured at a date. A balance-sheet amount is not a twelve-month total." },
  { id: "quarter", term: "Quarter · year to date (YTD)", category: "Periods", definition: "A quarter covers one reporting quarter. YTD accumulates flows from the fiscal year's start through the stated date.", detail: "A six-month YTD amount is not the second quarter alone. Deriving a quarter requires compatible cumulative periods, source editions and an explicit transform." },
  { id: "ttm", term: "Trailing twelve months (TTM)", category: "Periods", definition: "Twelve months of eligible financial flows ending at the stated reporting date. This is historical performance, not a forecast.", detail: "The calculation layer assembles compatible annual, quarterly or reviewed annual/YTD inputs. It does not add overlapping rows or reconstruct EPS by summing convenient per-share figures." },
  { id: "yoy", term: "Year over year (YoY)", category: "Periods", definition: "A period compared with the corresponding period one year earlier.", detail: "Quarter YoY compares the same quarter in different years. It does not compare with the immediately preceding quarter. Unsupported reporting calendars remain explicit gaps." },
  { id: "revenue", term: "Revenue · revenue growth", category: "Fundamentals", definition: "Revenue is the amount earned from selling goods or services over a period. Growth is current revenue ÷ compatible prior revenue − 1; it is displayed as a percentage.", detail: "Illustration: 100 to 120 is 20% growth. A nonpositive prior base does not support this growth percentage. Growth alone establishes neither profit nor cash generation." },
  { id: "gross-margin", term: "Gross profit · gross margin", category: "Fundamentals", definition: "Gross profit is revenue after the matching cost of revenue. Gross margin is gross profit ÷ positive revenue.", detail: "Reported gross profit and a derived revenue-minus-cost result retain distinct evidence. The margin does not by itself prove healthy unit economics." },
  { id: "operating-margin", term: "Operating income · operating margin", category: "Fundamentals", definition: "Operating income reflects operating expenses as well as cost of revenue. Operating margin is operating income ÷ positive revenue.", detail: "Operating income is not automatically EBIT. Negative margins can be meaningful; inspect the source amounts and scale before interpreting an extreme ratio." },
  { id: "net-margin", term: "Net income · net margin", category: "Fundamentals", definition: "Net income includes effects from financing, taxes and other items. Net margin here uses matching consolidated net income ÷ positive revenue.", detail: "Consolidated income, income attributable to the parent and income available to common shareholders have different scopes. Equal amounts do not make them interchangeable." },
  { id: "cfo", term: "Cash flow from operations (CFO)", category: "Fundamentals", definition: "Cash generated or used by operating activities during the stated period, reported in currency units.", detail: "Profit and operating cash flow differ because of noncash items and the timing of cash receipts and payments. A difference prompts inspection; it is not proof of poor accounting." },
  { id: "capex", term: "Capital expenditure (capex)", category: "Fundamentals", definition: "For the implemented cash-flow convention, capex means cash purchases of property, plant and equipment (PPE), recorded as a reviewed nonnegative outflow.", detail: "Reported zero is valid. An unexpected negative amount must be investigated, not converted to its absolute value. This definition may differ from an issuer's adjusted capex." },
  { id: "fcf", term: "Free cash flow (FCF) · FCF margin", category: "Fundamentals", definition: "The current convention is CFO − cash purchases of PPE. FCF margin is that FCF ÷ positive revenue.", detail: "Illustration: CFO of 12, PPE capex of 20 and revenue of 100 produce FCF of −8 and an FCF margin of −8%. This is not FCFF, issuer-adjusted FCF or automatically cash distributable to shareholders." },
  { id: "cash-debt", term: "Cash · debt · net cash", category: "Fundamentals", definition: "Cash is a balance at a date; debt represents specified financing obligations. Net cash compares eligible cash with debt under an explicit definition.", detail: "Restricted cash, customer assets and stablecoin-holder reserves cannot silently become corporate cash. Debt, lease and other claim treatment must be stated; missing claims are not zero." },
  { id: "eps", term: "Earnings per share (EPS)", category: "Fundamentals", definition: "Earnings attributable to the relevant shareholders divided by a compatible weighted-average share count, expressed in currency per share.", detail: "Basic, diluted, reported, adjusted and forecast EPS are distinct. Diluted EPS can require different numerator adjustments and anti-dilution rules. Period-end shares are not a substitute for weighted-average shares." },
  { id: "dilution", term: "Dilution · stock-based compensation (SBC)", category: "Fundamentals", definition: "Dilution changes the claim represented by a share as the share base changes. SBC is an accounting expense for compensation paid using equity instruments.", detail: "SBC expense is not identical to actual share-count dilution. Check issuances, repurchases, outstanding awards, share classes and the reporting period separately." },
  { id: "pe", term: "P/E · trailing P/E", category: "Valuation ratios", definition: "A price-to-earnings multiple, displayed in times (×). The current sector calculation uses common-equity capitalization ÷ matching income available to common shareholders.", detail: "A compatible per-share price/EPS definition is a separate basis. A nonpositive earnings denominator is N/M. Trailing earnings are reported history; forward earnings are estimates." },
  { id: "ps", term: "P/S", category: "Valuation ratios", definition: "Common-equity capitalization divided by eligible revenue, displayed in times (×). Sector total divides sums from the same matched cohort.", detail: "It relates equity value to sales, not to profit or cash flow. The revenue denominator must satisfy the metric's positive-base and precision rules." },
  { id: "pfcf", term: "P/FCF", category: "Valuation ratios", definition: "Common-equity capitalization divided by FCF under the stated CFO-minus-PPE-capex convention, displayed in times (×).",
    detail: "Nonpositive FCF is N/M for a company multiple. Known negative FCF remains in an eligible sector-total denominator; a nonpositive total is also N/M." },
  { id: "sector-total", term: "Sector total · aggregate ratio", category: "Sector methods", definition: "Combine eligible amounts first, then divide. Total P/E is summed common-equity capitalization ÷ the same companies' summed common-shareholder earnings.", detail: "Known losses remain in the aggregate. This is not the average or median of profitable companies' P/Es. The matching cohort, exclusions and coverage are part of the result." },
  { id: "median", term: "Median company", category: "Sector methods", definition: "The middle of the eligible company ratios, describing a typical company in that distribution.", detail: "Companies whose multiple is not meaningful are excluded from that ratio distribution and disclosed. Their known losses can still contribute to the sector-total method." },
  { id: "simple-mean", term: "Simple mean", category: "Sector methods", definition: "The arithmetic average of eligible company ratios: sum the ratios and divide by their count.", detail: "Extreme ratios can dominate. It is not a capitalization-weighted sector ratio; inspect the full distribution and exclusions before comparing it with the median." },
  { id: "breadth", term: "Growth · profit · cash breadth", category: "Sector methods", definition: "The fraction of companies with eligible known observations that have positive growth, common earnings or FCF, respectively. Displayed as a percentage.", detail: "Unchanged and declining observations stay in growth breadth's denominator. Missing amounts never become losses. Breadth uses equal-company counts rather than the multiple-method controls." },
  { id: "n-k-v", term: "N · K · V", category: "Coverage", definition: "N is every issuer in the independently declared roster. K is the issuers with complete eligible inputs for the metric. V is the companies contributing to the selected calculation method.", detail: "Known losses and zeros can count in K even when their company multiple is N/M. Switching from sector total to a company distribution can change V; it must not silently change the declared universe." },
  { id: "coverage", term: "Issuer coverage · capitalization coverage", category: "Coverage", definition: "Issuer coverage is K/N. Capitalization coverage compares contributors' capitalization with complete roster capitalization.", detail: "If required full-roster capitalization is unknown, cap coverage is unavailable. The known subset cannot be presented as the whole denominator. Coverage describes observed inputs, not automatic suitability." },
  { id: "limited", term: "Limited coverage", category: "Coverage", definition: "A calculated result that does not meet the comparison policy. It can remain visible with an outlined bar and its limitations.", detail: "It does not enter numeric ranks, scatter comparisons or summary conclusions. The fictional development policy requires at least 10 contributors, 70% issuer coverage and 80% capitalization coverage; all three gates must pass." },
  { id: "concentration", term: "Concentration · growth excluding top five", category: "Sector methods", definition: "Concentration is the top five companies' share of complete sector capitalization. Growth excluding top five removes the same five companies, chosen by prior-date capitalization, from both revenue sums.", detail: "These answer different questions. Unknown full capitalization makes concentration unavailable; choosing today's leaders for both dates would change the historical comparison." },
  { id: "percentile", term: "Percentile · P25 · P50 · P75", category: "History", definition: "A location in an eligible sample. P25 and P75 bound its middle half; P50 is its median.", detail: "The calculation policy states the interpolation method and eligible sample. A low historical multiple is not proof of undervaluation; a percentile is not a forecast probability." },
  { id: "history-window", term: "Own history · 3Y / 5Y / 10Y", category: "History", definition: "Compare a company's metric with eligible observations in the selected three-, five- or ten-year window. Sector graph controls separately use one, three or five years.", detail: "Read sample dates, eligible and excluded counts, history mode and insufficiency reasons. Ten years selected must not silently become three years. No sufficient sample means no band or rank." },
  { id: "current-members", term: "Current members' history", category: "History", definition: "A reconstruction using today's constituent list across earlier dates.", detail: "It is not historical sector membership and cannot support historical-sector percentile claims. Historical membership needs classifications effective and known at each date." },
  { id: "missing", term: "Missing · source nil", category: "Data states", definition: "Missing means no usable fact was selected. Source nil means the source explicitly declares an absent value. Neither means zero.", detail: "A reported zero is a real observation. Missing data remains a gap with a reason; it is never interpolated or substituted with zero to complete a graph." },
  { id: "nm", term: "N/M · not meaningful", category: "Data states", definition: "The requested calculation fails its mathematical meaning rule, such as a P/E with nonpositive earnings.", detail: "N/M is not a measured zero or a negative valuation multiple. The underlying loss can remain visible and useful even when the ratio cannot be interpreted." },
  { id: "unsupported", term: "N/A · not applicable · unsupported", category: "Data states", definition: "A metric may not apply to this business, or the required calculation, source or evidence may not yet be supported.", detail: "The reason matters: not applicable, missing input and unimplemented support are different states. Read the explanation attached to a dash or unavailable result." },
  { id: "stale", term: "Stale · invalid · quality flag", category: "Data states", definition: "Stale data exceeds the selected age policy. Invalid inputs fail a required check. A quality flag records a problem affecting interpretation or readiness.", detail: "A preserved fact can be inspectable while a dependent result is blocked. A new retrieval time does not make an old observation fresh." },
  { id: "precision", term: "Source precision · unit · scale", category: "Evidence", definition: "Precision records source rounding information. Units identify what a value measures; scale expands the written amount, such as currency in millions.", detail: "A denominator indistinguishable from zero at source precision cannot support a stable ratio. Precision is not guessed from display digits. 12 in millions denotes 12,000,000 of the stated unit." },
  { id: "provenance", term: "Provenance · accession · transform", category: "Evidence", definition: "The trace from a displayed result to its source, exact filing and archived response, through the selected operands and formula. An accession identifies a specific SEC filing.", detail: "Inspect the source identity, original tag, dates, licence and transform chain. A derived amount does not overwrite its reported source facts." },
  { id: "dates", term: "Reporting date · filing date · retrieval time", category: "Evidence", definition: "The reporting period says what time the fact describes. The filing date says when it was filed. Retrieval time says when this application captured it.", detail: "An old reporting period downloaded today was not necessarily known to this workspace in the past. Date-only release evidence cannot establish availability at a particular hour." },
  { id: "history-mode", term: "As filed by date · latest reported · restatement", category: "Evidence", definition: "As filed by date restricts evidence to filings available by that date. Latest reported selects the eligible later reporting version under the pinned policy. A restatement corrects earlier financial information.", detail: "Both versions and their filing dates are retained. Never mix them silently in a historical series; latest reported does not mean the source was fetched today." },
  { id: "snapshot", term: "Snapshot · rerun · retry", category: "Evidence", definition: "A snapshot identifies one frozen result and its inputs. A rerun creates a new request with preserved history; a retry is another attempt to finish the same request.", detail: "A failed refresh must not relabel an earlier result as fresh. Read its original snapshot and date separately from the latest failure." },
  { id: "equity-ev", term: "Equity value · enterprise value (EV)", category: "Valuation · planned", definition: "Equity value concerns shareholders' claims. Enterprise value relates operating value to the defined financing claims and eligible cash adjustments.", detail: "The debt, cash, lease, minority-interest and share-class definitions must match the valuation. Do not pair an EV numerator with a cash-flow denominator intended for a different set of claimants." },
  { id: "dcf", term: "DCF · reverse DCF", category: "Valuation · planned", definition: "Discounted cash flow estimates value from explicit future cash-flow assumptions. Reverse DCF asks which assumptions would be needed to support the observed price.", detail: "These workspaces are planned. Results must be ranges with assumptions and sensitivity, never a buy/sell instruction or an editable conclusion." },
  { id: "fcff-wacc", term: "FCFF · WACC · terminal value", category: "Valuation · planned", definition: "FCFF is free cash flow to the firm. WACC is the weighted average cost of capital for compatible enterprise cash flows. Terminal value represents the period beyond the explicit forecast.", detail: "FCFF is not the current CFO-minus-PPE-capex FCF measure. Discount-rate inputs, reinvestment and terminal assumptions need dated evidence or explicit human rationale; these models are not active here." },
  { id: "sensitivity", term: "Sensitivity · probability", category: "Research", definition: "Sensitivity shows how an output changes when an input changes. Probability describes the assessed likelihood of an event or outcome.", detail: "A sensitivity range is not automatically a probability interval. More scenarios do not create evidence for their assigned likelihoods." },
  { id: "inflation", term: "CPI · PPI · core · headline", category: "Macro · planned", definition: "CPI concerns consumer prices; PPI concerns prices received by producers. Headline covers the full specified index; core excludes components defined by that series, commonly food and energy.", detail: "Check the exact series, units, seasonal adjustment and month-over-month or year-over-year period. A scheduled release is not yet an observed value; macro news monitoring is not active in this build." },
  { id: "fed", term: "Fed · FOMC · yield", category: "Macro · planned", definition: "The Federal Reserve is the US central bank. The FOMC makes monetary-policy decisions. A yield is a return measure attached to a specified instrument and date.", detail: "A Treasury yield, the effective federal funds rate and a policy target range are different measures. There is no guaranteed stock-price response to a policy announcement." },
  { id: "basis-points", term: "Percent · percentage point · basis point", category: "Units", definition: "One basis point is one hundredth of a percentage point. A change in a percentage level is different from its relative percentage change.", detail: "Illustration: a margin rising from 10% to 12% gains 2 percentage points, or 200 basis points. It has not risen by 2% on a relative basis." },
  { id: "consensus", term: "Consensus · surprise · revision", category: "Macro · planned", definition: "Consensus is a third-party expectation, not an observed fact. A surprise compares a release with a compatible expectation. A revision changes an earlier released observation.", detail: "Retain actual, consensus and prior values separately with dates and units. Preserve the original release alongside corrections. Consensus is not an input to the user's DCF assumptions." },
  { id: "confidence", term: "Assessment confidence · source reliability", category: "News · planned", definition: "Confidence concerns the strength of an interpretation. Source reliability concerns the evidence source. These are separate judgments.", detail: "A reliable announcement may still have an uncertain business impact. Assessments need a mechanism, horizon, materiality, counterevidence and what would change the conclusion." },
  { id: "change-explanation", term: "Why did this change?", category: "Research · planned", definition: "A proposed view separating deterministic numerical contributions from evidence-based explanations of possible business causes.", detail: "A ratio's arithmetic can show how its inputs changed without proving why they changed. Filing or news evidence, alternatives and uncertainty are needed before making a causal claim." },
  { id: "expectation", term: "Expectation · falsification · review", category: "Research · planned", definition: "A saved expectation records what you think will happen, why, supporting evidence, what would weaken it and a dated review or falsification condition.", detail: "The planned earnings review compares new evidence with the original reasoning. Retain, revise or retire creates a traceable history; it must not overwrite the earlier expectation." },
];

export default function HelpPage() {
  return <WorkbenchShell active="help"><main id="main-content" tabIndex={-1} className={`workspace-page help-page ${styles.page}`}>
    <header className={styles.intro}>
      <div><p className="eyebrow">RESEARCH COMPANION</p><h1>Help & terminology<span className="title-dot">.</span></h1>
        <p>Read the graphs, inspect the evidence, and understand what each result can tell you.</p></div>
      <p className={styles.version}>Development guide · 20 September 2026<br />Fictional demos & archived sources · live services inactive</p>
    </header>

    <div className={styles.notice}><strong>Start with the data label.</strong><p>The Sector and Company demonstrations use explicitly fictional, offline calculation results. The separate Real-data pilot shows archived SEC observations with incomplete coverage. Neither is a live valuation service. Production data prerequisites remain visible on <Link href="/sectors">Data readiness</Link>.</p></div>

    <div className={styles.layout}>
      <nav className={styles.contents} aria-label="Help contents"><p className="eyebrow">IN THIS GUIDE</p>
        <a href="#start">A five-minute first pass</a><a href="#real-source-pilot">Read the real-data pilot</a><a href="#sectors">Read Sector Explorer</a><a href="#company">Read company fundamentals</a><a href="#evidence">Check evidence & history</a><a href="#glossary">Find a definition</a><a href="#planned">What comes next</a><a href="#troubleshooting">Troubleshooting & printing</a>
      </nav>
      <div className={styles.chapters}>
        <section id="start" className={styles.section} aria-labelledby="start-title"><div className={styles.sectionHeading}><span className="eyebrow">01 / START HERE</span><h2 id="start-title">A five-minute first pass</h2></div>
          <ol className={styles.steps}>
            <li><strong>Set the comparison.</strong><p>Open <Link href="/development/sectors">Sector Explorer</Link>. Read the fictional-data banner, universe, evaluation date, period and currency. Choose the measure and calculation method before comparing bars.</p></li>
            <li><strong>Check whether the result is usable.</strong><p>Read N, K, V and both coverage measures. An outlined bar has limited coverage. A missing bar is not zero. Open its value or coverage cell to learn why.</p></li>
            <li><strong>Look behind the group.</strong><p>Select a sector, compare its history and company distribution, then select a distribution bin. Search or pin a company in the constituents table and open its source evidence.</p></li>
            <li><strong>Review the company in context.</strong><p>Open the <Link href="/development/company">Company demonstration</Link>. Separate growth, profitability, cash generation, balance sheet, and valuation/returns. Read each missing or unsupported reason rather than inferring a result.</p></li>
            <li><strong>Keep the question separate from the verdict.</strong><p>A cheap-looking ratio is a starting question. Check the business model, reporting scope, source dates and alternatives. Saved expectations, full analysis reruns and valuation ranges remain planned workflows.</p></li>
          </ol>
        </section>

        <section id="real-source-pilot" className={styles.section} aria-labelledby="pilot-title"><div className={styles.sectionHeading}><span className="eyebrow">ARCHIVED SOURCES / SMALL PILOT</span><h2 id="pilot-title">Real evidence, explicit gaps</h2></div>
          <p>Open the <Link href="/development/pilot">Real-data pilot</Link> and choose CRCL, MSTR, COIN, HOOD, USAR, MP or GOOGL. This route is separate from the fictional Company and Sector demonstrations. Its real-source banner identifies archived SEC observations, incomplete coverage and no live prices.</p>
          <ol className={styles.steps}><li><strong>Confirm the instrument.</strong><p>Read the CIK, exchange, security description, identity evidence and dated business context. A ticker alone is insufficient.</p></li><li><strong>Distinguish research from observed values.</strong><p>The filing reviewed for company context can be newer than the filing behind the displayed financial amounts. Check both period and filing dates; archive capture time is a separate date.</p></li><li><strong>Open each supplied amount.</strong><p>Its evidence identifies the reported concept, source, units and period. Companies without qualified observations keep an explicit gap; fictional values and zero are never substituted.</p></li><li><strong>Read the remaining prerequisites.</strong><p>Derived metrics are unavailable in this source-only slice. The 3Y/5Y/10Y controls keep requested dates and coverage visible without inventing a graph, percentile or rank. The seven companies are not a sector universe or one peer group.</p></li></ol>
        </section>

        <section id="sectors" className={styles.section} aria-labelledby="sectors-title"><div className={styles.sectionHeading}><span className="eyebrow">02 / SECTOR EXPLORER</span><h2 id="sectors-title">Four graphs, one dated comparison</h2></div>
          <div className={styles.guideGrid}>
            <article><h3>Sector comparison</h3><p>Choose <strong>Sector total</strong> to divide summed amounts, or <strong>Median company</strong> for a typical eligible company ratio. <strong>Simple mean</strong> is an advanced method sensitive to outliers. A numerical sort is not an investment ranking.</p></article>
            <article><h3>Through time</h3><p>Select up to four sectors and a <strong>1Y, 3Y or 5Y</strong> window. Patterns distinguish series. Gaps remain gaps. Read whether the result uses historical membership or current members&apos; history.</p></article>
            <article><h3>Company distribution</h3><p>Choose a bin to filter constituents. Search composes with the bin filter; clear the bin to broaden the table. Pin a row for inspection. Excluded or N/M companies still have disclosed reasons and evidence.</p></article>
            <article><h3>Growth versus valuation</h3><p>Read growth and trailing P/E as separate dimensions. Groups that fail eligibility are listed as unavailable rather than plotted at zero. Position and color do not recommend buying or selling.</p></article>
          </div>
          <div className={styles.example}><span className="eyebrow">ILLUSTRATIVE METHOD EXAMPLE</span><p>Three companies each worth 100 have earnings of 10, 1 and −9. <strong>Sector total P/E is 150×</strong> (300 ÷ 2). The two meaningful company P/Es are 10× and 100×, so their <strong>median and simple mean are 55×</strong>. Excluding the loss from the total would answer a different question.</p></div>
          <h3 className={styles.subheading}>Coverage travels with the number</h3>
          <dl className={styles.inlineDefinitions}><div><dt>N · declared roster</dt><dd>Every issuer, including missing and unsupported companies.</dd></div><div><dt>K · eligible inputs</dt><dd>Companies with complete eligible metric inputs. A known loss or zero can count.</dd></div><div><dt>V · contributors</dt><dd>Companies used by the selected method. It can change when the method changes.</dd></div></dl>
          <p>Data coverage is K/N. Capitalization coverage requires complete roster capitalization; an unknown denominator stays unavailable. The current fictional comparison gates require at least ten contributors, 70% issuer coverage and 80% capitalization coverage. A visible limited value is not eligible for a numerical rank or scatter comparison.</p>
          <p className={styles.note}>The market reference uses the same selected metric, method and date with its own disclosed universe and coverage. Open it to inspect the evidence; it is not an automatically comparable external benchmark.</p>
        </section>

        <section id="company" className={styles.section} aria-labelledby="company-title"><div className={styles.sectionHeading}><span className="eyebrow">03 / COMPANY FUNDAMENTALS</span><h2 id="company-title">Read the amount before the ratio</h2></div>
          <p>Choose a fictional company and evaluation date in the Company demonstration. The view uses the same frozen snapshots as Sector Explorer. Its available basis is TTM; quarterly and annual paths stay visibly unavailable. A source amount can be inspectable even when a related comparison or ratio is unavailable.</p>
          <ol className={styles.steps}>
            <li><strong>Growth.</strong><p>Compare revenue with a compatible prior period. Quarter YoY, an annual change and TTM describe different intervals; a nonpositive prior base does not support the usual growth percentage.</p></li>
            <li><strong>Profitability.</strong><p>Separate gross, operating and net margins. Gross margin is not proof of viable unit economics. Financing and taxes can affect net income without changing operating income.</p></li>
            <li><strong>Cash generation.</strong><p>Compare CFO, PPE capex and FCF. Here, FCF = CFO − cash purchases of PPE. It is not FCFF, issuer-adjusted FCF or automatically cash available to shareholders.</p></li>
            <li><strong>Balance sheet.</strong><p>Inspect cash, debt, claim scope and the balance-sheet date. Restricted or customer/reserve cash is not automatically available to the company. Unavailable fields remain gaps.</p></li>
            <li><strong>Valuation & returns.</strong><p>Read the precise numerator and denominator. P/E based on capitalization and common earnings is not silently interchangeable with price/EPS. A low multiple is not a valuation conclusion.</p></li>
          </ol>
          <div className={styles.callout}><h3>Keep the long view available</h3><p>Company own-history choices are <strong>3Y, 5Y and 10Y</strong>, separate from sector graph windows. The selected period must stay visible even if evidence is insufficient. An unavailable comparison must explain its missing sample dates, counts or prerequisites; it cannot silently shorten the window.</p></div>
          <p className={styles.note}>This fixture supplies only two company snapshot dates: 31 March and 30 June 2026. Every 3Y/5Y/10Y selection therefore shows insufficient history; no percentile or rank is produced. The longer sector series cannot substitute for company history. Complete company history, additional metrics and production result services remain planned.</p>
        </section>

        <section id="evidence" className={styles.section} aria-labelledby="evidence-title"><div className={styles.sectionHeading}><span className="eyebrow">04 / EVIDENCE & HISTORY</span><h2 id="evidence-title">One value, a traceable source</h2></div>
          <p>In Sector Explorer, open a bar, financial value or coverage cell to inspect source details. Company source controls inspect the same selected company snapshot. Use the accompanying tables for exact values and keyboard access. The detail belongs to the frozen snapshot used in the graph; it must not quietly open a newer company result.</p>
          <dl className={styles.inlineDefinitions}><div><dt>What does it measure?</dt><dd>Check units, scale, company/shareholder scope and the reporting period.</dd></div><div><dt>Where did it come from?</dt><dd>Check source name, filing/accession or URL, original concept, source licence and retrieval time.</dd></div><div><dt>How was it derived?</dt><dd>Check operands, formula, transformations, quality flags, exclusions and the snapshot identity.</dd></div></dl>
          <h3 className={styles.subheading}>Three dates answer different questions</h3><p>The <strong>reporting period</strong> describes the business activity. The <strong>filing date</strong> says when a report was filed. The <strong>retrieval time</strong> records when this workspace captured the source. Downloading old observations today does not prove this workspace held them last year.</p>
          <p><strong>As filed by date</strong> and <strong>latest reported</strong> are distinct modes. A later restatement must not silently replace the earlier version in a historical comparison. Date-only publication evidence cannot establish what was known at a particular hour.</p>
          <div className={styles.callout}><h3>A gap is information</h3><p>Missing, N/M, not applicable, unsupported, stale and invalid have different reasons. None means zero. A previous successful result can remain inspectable after refresh failure with its original date; it must not be labelled as newly recomputed.</p></div>
        </section>

        <section id="glossary" className={styles.section} aria-labelledby="glossary-title"><div className={styles.sectionHeading}><span className="eyebrow">05 / TERMINOLOGY</span><h2 id="glossary-title">Plain-language definitions</h2></div>
          <p>Search definitions, units and limitations. “Planned” identifies concepts whose complete product workflows are still to come.</p><Glossary entries={glossary} />
        </section>

        <section id="planned" className={styles.section} aria-labelledby="planned-title"><div className={styles.sectionHeading}><span className="eyebrow">06 / PRODUCT BOUNDARIES</span><h2 id="planned-title">What comes next</h2></div>
          <div className={styles.roadmapRows}>
            <article><span className={styles.status}>Planned</span><div><h3>Watchlist & full analysis</h3><p>Resolve the exact listing, add it, follow each source/calculation stage, confirm missing assumptions, rerun and compare preserved results. The pilot is CRCL, MSTR, COIN, HOOD, USAR, MP and GOOGL. Those seven stocks are not a complete sector universe or a single peer group.</p></div></article>
            <article><span className={styles.status}>Planned</span><div><h3>News & economic calendar</h3><p>Macro events and relevant company, competitor, regulatory and product developments need sourced facts, conditional assessments, counterevidence and revision history. Collection, assessment and delivery health are separate. In-app, desktop and email alerts are not live.</p><p>Quiet hours will delay delivery while collection continues. A local worker cannot collect while the machine is asleep; catch-up and last successful checks must be visible. Continuous coverage requires an available runtime.</p></div></article>
            <article><span className={styles.status}>Planned</span><div><h3>Change explanations & expectations</h3><p>Separate the arithmetic of a change from possible business causes. Save the expectation, evidence, what would weaken it and a dated review condition. Compare new earnings with the original reasoning, then retain, revise or retire without overwriting history.</p></div></article>
            <article><span className={styles.status}>Planned</span><div><h3>Business profiles & valuation</h3><p>Profiles describe company and segment economics, lifecycle and instrument with dated evidence. MSTR&apos;s treasury and software activities need distinct treatment; mineral projects need development-stage context. Supported models depend on the profile and inputs, with ranges and explicit assumptions.</p></div></article>
          </div>
        </section>

        <section id="troubleshooting" className={styles.section} aria-labelledby="troubleshooting-title"><div className={styles.sectionHeading}><span className="eyebrow">07 / WHEN SOMETHING IS UNAVAILABLE</span><h2 id="troubleshooting-title">Inspect the reason, then the source</h2></div>
          <div className={styles.guideGrid}><article><h3>There is no sector point</h3><p>Read the unavailable list and coverage details. Missing inputs, a nonmeaningful ratio or a failed coverage gate should not create a point at zero.</p></article><article><h3>A table looks empty</h3><p>Check the selected sector or industry, search text and distribution-bin filter. Clear the bin or search. If no constituents qualify, keep the empty-state reason visible.</p></article><article><h3>The history has gaps</h3><p>Check eligible dates, excluded observations, classification history and the selected window. More years requested does not create more evidence.</p></article><article><h3>No current data or alerts</h3><p>This build does not activate live providers or alerts. Visit <Link href="/sectors">Data readiness</Link>. A provider key alone does not establish source rights, reviewed definitions or complete coverage.</p></article></div>
          <div className={styles.callout}><h3>Print or save this guide</h3><p>Use your browser&apos;s <strong>Print</strong> command, then choose paper or <strong>Save as PDF</strong>. The print view uses this same guide and includes every glossary entry, even if a search is active. This is a development guide; the complete release manual will be checked against the finished watchlist, analysis and alert workflows.</p></div>
        </section>
        <footer className={styles.footer}>Guide version: 2026-09-20 · Development interface · All numerical examples are illustrative. No investment recommendation is implied.</footer>
      </div>
    </div>
  </main></WorkbenchShell>;
}
